### ISSUE TITLE
Discussion: Git workflow

### ISSUE THREAD

**Issue by sukhbeersingh** [Seneca-CDOT/telescope#10]
We need to talk how we’re going to manage our git workflow. What branches will our repo have? 
I propose feature branches, that lead to develop which finally builds to master.

**Comment by humphd** [comment]
I think at this point we're treaing `master` as deployment/integration target, and using feature branches.  Our production builds are a ways off, and will likely not happen in git at all, but via docker images being pulled into our cluster.

Since we're on our way, and this hasn't got a lot of discussion, I'm going to close for now.  Let's re-open an issue on anything specific we come up with later that needs attention.
