### ISSUE TITLE
Warnings in /myfeeds

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#1002]
**What happened**:
When you hit the telescopeUrl/myfeeds in dev

![image](https://user-images.githubusercontent.com/18711727/79259397-a5adab00-7e5a-11ea-88b9-c3140ee7830c.png)

**What should have happened**:
There shouldn't be these errors

**How to reproduce it (as precise as possible)**:
`npm run build`
`npm run develop`
login using user2/user2pass
`locahost:3000/myfeeds`

**Anything else we need to know?**:

**Environment**:

- OS: Windows 10 Professional
- Browser: Chrome

**Comment by cindyledev** [comment]
This bug is weird, if you refresh the page, some of these errors go away...

**Comment by Silvyre** [comment]
> This bug is weird, if you refresh the page, some of these errors go away...

Yeah, I've seen other errors behave this way... Makes it hard to track things down.

**Comment by Silvyre** [comment]
I imagine the first error is being caused by our banner:
https://github.com/Seneca-CDOT/telescope/blob/fd70912c43a432a4b635c4a5883f81968ae4b247/src/frontend/src/components/Banner/Banner.jsx#L263

If we pass it a `theme` prop like we do it our `TopLayout`...

https://github.com/Seneca-CDOT/telescope/blob/fd70912c43a432a4b635c4a5883f81968ae4b247/src/frontend/plugins/gatsby-plugin-top-layout/TopLayout.js#L18

...I imagine this would resolve that error.

**Comment by cindyledev** [comment]
The first one is easy to fix, we can get rid of <ThemeProvider> in `Banner.jsx`.

Second one needs more investigating

**Comment by cindyledev** [comment]
@Silvyre I tried just adding `theme={theme}` to the `<ThemeProvider>` in `Banner.jsx`
but it doesn't seem to like that because the `theme` in `TopLayout.js` is imported from `theme.js` so we can't use the same method in `Banner.jsx` as we did in `TopLayout.js`

`Banner.jsx` uses:
```
const useStyles = makeStyles((theme) -> ( {...} ) )
```
like every other component we have.
I wonder if we even suppose to use `<ThemeProvider>` with `makeStyles`

**Comment by Silvyre** [comment]
Would there be any repercussions to removing the banner's `<ThemeProvider>`, then?

**Comment by cindyledev** [comment]
I tested it and there doesn't seem to be any difference. When I was doing the makeStyles stuff in the Banner, I thought ThemeProvider was required but I guess not. I believe it's safe to remove it.

**Comment by Silvyre** [comment]
I think if we don't provide our own theme, we use MUI's [default theme](https://material-ui.com/customization/default-theme/) (which I suppose is the theme the banner is currently using).

**Comment by Silvyre** [comment]
I think I've figured out the second error:
https://github.com/Seneca-CDOT/telescope/blob/fd70912c43a432a4b635c4a5883f81968ae4b247/src/frontend/src/components/Posts/Posts.jsx#L19-L34

When `posts.length` is 0, we attempt to render `<Container>null</Container>`, which throws an error because `<Container>` needs to be passed children. I'll throw up a quick PR to fix these two issues.
