### ISSUE TITLE
Creating to-do-list on wiki page

### ISSUE THREAD

**Issue by cyh0968** [Seneca-CDOT/telescope#103]
Right now there are 59 issues in the repository. Since a lot of contributors are participating in a compact timeline, it is hard to catch up with new information. As a result, we can find several duplication issues. 

Perhaps, it is wasting to check if a similar issue exists already. Also, it is hard to see the whole picture and progress even though there is a project page.

If we make a list of works on the wiki page based on its modules or functionalities, it will be easy to check to see the workflow.

For instance, 

- Text Analysis - issue #7 assigned to someone
    - word count
    - reading the time- issue #19 assigned to someone fixed issue #19
    - writing level 
- Test
    - feed queue 

Then, we can save our time to find what we have to do. Besides, We can distribute our human resources based on priority.

**Comment by manekenpix** [comment]
I don't know, I think the search bar + filters + labels should be enough to keep track of what's going on. The search bar allows multiple types of filtering, and even the labels can help you isolate the area or type of issue one might be looking for.
I'm not sure about this, but I'd like to hear other people's opinions.

**Comment by Reza-Rajabi** [comment]
I am trying to keep track of things using the project board. It has not enough features though, so I am trying to find complementary solutions.
I agree that the labels and filters can give us enough tools to find our way out, but still, we can use other tools to make a map/picture from the whole project, identify conflicts, find bottlenecks that are specific for our project. For instance, for this small project with about 50 contributors which they have special needs as well as about 30 to 50 issues weekly or bi-weekly to work on, producing proper issues is crucial. If we could make the current To-Do list clean and update, we know where we are, and what we need to increase the successful pull request for everybody. Also, people can grab an issue from a summarized To-Do list. 
@cyh0968 I suggest to try what you are thinking about and let's see if we can bring your thoughts into the project board or we can ship the project board into the wiki. I am trying to find some gadgets to help us. This project is very hard to keep it clean because of its special scope, time frame, the number of people, rewarding by grades, and so on.

**Comment by Reza-Rajabi** [comment]
I just finished the project's board makeup and here is the project status right at this time:

- 10 ------ Discussions
- 04 ------ To-Do issues (not assigned tasks)
- 46 ------ Active issues (assigned/under-review tasks)
- 14  ------ Jobs done (merged pull request)
- 18  ------ Closed task (issue/pull request)

So almost everybody has got something. Impressive no? It seems like we can live on the planet next week after about maybe 20 merged pull requests.

**Comment by cyh0968** [comment]
> I am trying to keep track of things using the project board. It has not enough features though, so I am trying to find complementary solutions.
> I agree that the labels and filters can give us enough tools to find our way out, but still, we can use other tools to make a map/picture from the whole project, identify conflicts, find bottlenecks that are specific for our project. For instance, for this small project with about 50 contributors which they have special needs as well as about 30 to 50 issues weekly or bi-weekly to work on, producing proper issues is crucial. If we could make the current To-Do list clean and update, we know where we are, and what we need to increase the successful pull request for everybody. Also, people can grab an issue from a summarized To-Do list.
> @cyh0968 I suggest to try what you are thinking about and let's see if we can bring your thoughts into the project board or we can ship the project board into the wiki. I am trying to find some gadgets to help us. This project is very hard to keep it clean because of its special scope, time frame, the number of people, rewarding by grades, and so on.

I checked the project board. I agree that the issues and the project board are pretty cool. However, as you mentioned, it will be really nice to view the whole picture. And I realized that if one or two people manage the to-do-list on wiki page, it would be annoying and uncomfortable. I think we can use Github extension.  I found [an article](https://everhour.com/blog/project-management-using-github/) about GitHub project management tools. I will look for tools we can use it.

**Comment by Reza-Rajabi** [comment]
@cyh0968 Great!

**Comment by Reza-Rajabi** [comment]
@cyh0968 Hi, I was just wondering how this issue is going?

**Comment by c3ho** [comment]
Closing this issue as we're moving towards Github projects to track status of ongoing issues.
