### ISSUE TITLE
Help clarify ownership of feed vs. content

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1037]
<img width="823" alt="Screen Shot 2020-04-21 at 3 55 41 PM" src="https://user-images.githubusercontent.com/427398/79908084-a3ae9380-83e8-11ea-9c30-3d816c1f92e7.png">

An authenticated user can add a feed to Telescope.  Such a feed could be one they write, or one they want to see included in our timeline.

Our UI makes it seem like the person who added the feed is its owner.

In the case above, the feed probably should have been added with an Author (Mozilla) different from the Owner (Calvin).  So maybe this is user error?  If so, we need to help users not make this mistake.

Or maybe we need to figure out how to not make this confusing in the UI with how we show the "Author".

**Comment by c3ho** [comment]
I’ll take a look at this

**Comment by c3ho** [comment]
The line here: https://github.com/Seneca-CDOT/telescope/blob/c8581c359c51e390a55ebdcc6bac85bfdcfce204/src/frontend/src/components/Posts/Posts.jsx#L24

is working as expected, it fetches whatever is from the DB. I think this is the problematic line when we're adding the feed.

https://github.com/Seneca-CDOT/telescope/blob/c8581c359c51e390a55ebdcc6bac85bfdcfce204/src/frontend/src/pages/myfeeds.js#L93

https://github.com/Seneca-CDOT/telescope/blob/c8581c359c51e390a55ebdcc6bac85bfdcfce204/src/backend/web/routes/feeds.js#L59

How do you propose we fix this? We have 3 fields when adding a feed: `user`, `author` and `url`. 
1. Should we only accept url, add the feed to the queue and let it sort it out?
2. Should we change it so that Post has another field for Author?
3. Should we just make a front end change and say like "From a feed added by: (author)", but not as verbose?

**Comment by Silvyre** [comment]
> In the case above, the feed probably should have been added with an Author (Mozilla) different from the Owner (Calvin). So maybe this is user error? If so, we need to help users not make this mistake.

I assume this _is_ a case of user error... Testing locally, I am able to add a new feed via the My Feeds, e.g.

![image](https://user-images.githubusercontent.com/13500769/79931179-63670980-8418-11ea-953b-0273e2eced90.png)

And blog posts from this feed reflect the input author name:

![image](https://user-images.githubusercontent.com/13500769/79931154-53e7c080-8418-11ea-9148-f5167c990cec.png)

**Comment by humphd** [comment]
I'm inclined to agree that our backend is fine, and we need to provide some help in the frontend to guide users to do the right thing.

In the Add Feed UI, should we somehow ask the user if they "own this feed," and if NO, then we give them a spot to enter the name of the feed's author.

Right now we just stick your name in the Author field, so it's natural that people will ignore it.

**Comment by chrispinkney** [comment]
Closing, added a reference note to #1643 as this issue is not necessary any longer.
