### ISSUE TITLE
Increase contrast in post header

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1055]
<img width="724" alt="Screen Shot 2020-04-23 at 2 03 36 PM" src="https://user-images.githubusercontent.com/427398/80133483-4858de80-856b-11ea-87e3-38cf4601beb7.png">

Caused by:

<img width="354" alt="Screen Shot 2020-04-23 at 2 04 21 PM" src="https://user-images.githubusercontent.com/427398/80133521-59095480-856b-11ea-9240-43b75d6a3701.png">

This needs to get fixed so it's more accessible.

**Comment by agarcia-caicedo** [comment]
I played around with some colours, and I think its better to just use two colours for the post header. Otherwise the only colours we could use would be a blue, white, and black.

![image](https://user-images.githubusercontent.com/49992710/81254998-8853a300-8ffa-11ea-86d7-d25f95045079.png)

![image](https://user-images.githubusercontent.com/49992710/81254926-622e0300-8ffa-11ea-8be4-828259e3b74f.png)
This one keeps the dark to #002944, but changes the blue to #5995C9

![image](https://user-images.githubusercontent.com/49992710/81255116-da94c400-8ffa-11ea-8ab6-59dc7f5df06d.png)

![image](https://user-images.githubusercontent.com/49992710/81255144-eb453a00-8ffa-11ea-97ba-9c819b456503.png)
This one keeps the light colour to #A4D4FF, but changes the blue to #2A5A83

![image](https://user-images.githubusercontent.com/49992710/81255408-8dfdb880-8ffb-11ea-96ab-a8c61ad97508.png)

![image](https://user-images.githubusercontent.com/49992710/81255494-c43b3800-8ffb-11ea-9cde-6970e7de4217.png)
This one keeps the blue at #3670A5, but changes the light to #AFFDFC

The blue doesn't work well with any dark colour, so I can't present a variation

**Comment by cindyledev** [comment]
Gives me dark mode vibes #77 ;)

**Comment by humphd** [comment]
@strawberries73 is going to give this a try.

**Comment by strawberries73** [comment]
@humphd  Do I need to stick with the "blue" theme?

**Comment by humphd** [comment]
Yes, this isn't about changing colour, only contrast.  @agarcia-caicedo has already done colour theming in other PRs.

**Comment by humphd** [comment]
Confirmed this was fix with light theme changes, closing.  Sorry Jenn, we'll find you another bug.
