### ISSUE TITLE
Banner Images Reload twice

### ISSUE THREAD

**Issue by raygervais** [Seneca-CDOT/telescope#1078]
**What happened**:

We are currently processing all images in a GraphQL query, and then selecting `after` with a randomized function. Instead, we should have GraphQL return a single randomized image instead. This came about when #1043 was merged.

**Comment by humphd** [comment]
Part of the fix for this is to refactor `src/frontend/src/pages/index.js`.  Right now we have the header banner image in with the posts, and this is where the `useEffect()` logic for reloading the page is happening.  Whenever this triggers the need for a re-render, the banner is also being re-rendered.

The banner should render once, and never again.  If we split this page up into separate components, and move the state handling/invalidating further down in the component tree, this won't be an issue.

Because there's no dependency between `<Posts>` and `<Banner>`, let's move all this data logic into `<Posts>`.

**Comment by PedroFonsecaDEV** [comment]
Hi, this problem is still open?
If so I would like to give a try. 
Thanks

**Comment by manekenpix** [comment]
@PedroFonsecaDEV sure, go ahead!

**Comment by PedroFonsecaDEV** [comment]
Okay. Thanks.
Working on it.
