### ISSUE TITLE
CircleCI Docker Hub change

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1154]
I got this email today, do we need to worry about it? cc @raygervais 

>Hi there, 
>
>On November 1st, Docker Hub will begin limiting anonymous image pulls. We want to make sure you know how you might be impacted and what you can do to avoid interruptions to your workflow. 
>
>Adding Docker authentication to your pipeline config is the easiest way to avoid any service disruptions. If you use the Docker executor or pull Docker images when using the machine executor on CircleCI, we encourage you to authenticate. Because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP. 
>
>We are currently working on a partnership with Docker to minimize the impact of this change for our users and will share more details as we get them. 
>
>For more information or to leave a question for us, please head over to Discuss or contact support. 
>
>Thanks and happy building, 
>
>- The CircleCI team

**Comment by raygervais** [comment]
Adding an official Seneca-based account wouldn't hurt at all, because then we could also publish to Docker hub and reduce build times for example by having stable images published each release too. Given the amount of PRs I imagine October will bring, I'd be concerned that pipelines will start failing randomly due to the limit @humphd.

@manekenpix and I could look into this, we were discussing Actions and taking Docker even further in the project this week.

**Comment by humphd** [comment]
We've removed CircleCI, closing.
