### ISSUE TITLE
'Search' returns latest posts instead of results for searched input.

### ISSUE THREAD

**Issue by manekenpix** [Seneca-CDOT/telescope#1169]
**What happened**:
I entered a string in the search box and it returned the latest posts instead of actual results

![Peek 2020-10-08 11-58](https://user-images.githubusercontent.com/23108901/95483987-e5fb6b00-095d-11eb-8f53-3ee888660cdc.gif)

**What should have happened**:
I should have seen posts related to the entered string

**How to reproduce it (as precise as possible)**:
Go to https://dev.telescope.cdot.systems/search, enter any string in the search box and compare results to latest posts in `/`

**Comment by manekenpix** [comment]
I think the origin of this is #1162. Our [search page](https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/SearchPage/SearchPage.jsx) relies on the `Posts` component to render search results (see [here](https://github.com/Seneca-CDOT/telescope/blob/5b7edcb6ba3760155b4a9621fcc2cc55055204f0/src/frontend/src/components/SearchPage/SearchPage.jsx#L147)), but after merging #1162, `Posts` [doesn't take any props](https://github.com/Seneca-CDOT/telescope/blob/5b7edcb6ba3760155b4a9621fcc2cc55055204f0/src/frontend/src/components/Posts/Posts.jsx#L42) and simple loads the latest posts.

**Comment by humphd** [comment]
Nice find!  Probably the right fix here is to abstract the idea of "showing posts" from getting those posts, so that we can have both posts and search results that share most of their code.  Could we pass down some query details to `<Posts>` with an optional `filter="..."` or something?

```jsx
// all recent posts by default
<Posts />

// posts by an author
<Posts author="..." />

// posts with search term
<Posts search="..." />

// posts by author with search term
<Posts search="..." author="..." />
```

Then it could use the query params if found on props, or do the default thing and load recent posts instead.  In both cases it will need to do a query and display, so the logic is essentially the same.
