### ISSUE TITLE
Improve accessibility of author search results

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1258]
We're using a `<button>` vs. an `<a>` for the search results of an author:

<img width="1038" alt="Screen Shot 2020-11-01 at 12 48 26 PM" src="https://user-images.githubusercontent.com/427398/97810272-abc17880-1c40-11eb-927a-89069deb0f84.png">

A `button` element is for triggering some action in the page, while an `a` element is for navigation.  They have different semantics and keyboard/mouse behaviours.

Since we're using these to navigate, they should be `<a>`.

**Comment by egrinberg** [comment]
Hey, I would like to work on this.

**Comment by humphd** [comment]
All yours @egrinberg

**Comment by egrinberg** [comment]
I investigated this issue and found the following:

In the AuthorResult.js, Card components are used. The <button> is created by the <CardActionArea> component. In order to fix the accessibility issue, we might need to use the Link component from 'react-router-dom'.

[link to the suggested solution](https://stackoverflow.com/a/50444524/11555213).

**Comment by egrinberg** [comment]
@humphd  This issue should be closed as the latest changes fix it. Posts in the timeline are not using the CardAction component.
