### ISSUE TITLE
Warning: Accessing non-existent property 'logger' of module exports inside circular dependency

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1262]
We have a warning we should fix on startup:

```
$ npm start
...
(node:21325) Warning: Accessing non-existent property 'logger' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
```

**Comment by klee214** [comment]
Hello, I think, it seems like because `src/backend/lib/config.js` require `backend/utils/logger.js` and at the same time `backend/utils/logger.js` also require `src/backend/lib/config.js`

ref:
1. [How to deal with cyclic dependencies in Node.js](https://stackoverflow.com/questions/10869276/how-to-deal-with-cyclic-dependencies-in-node-js)
2. [Circular Dependencies in Node](https://ericclemmons.com/blog/circular-dependencies-in-node)

I am not sure my assumption is correct or not, but I will give it a shot anyway! If I am wrong or there is anything I need to consider or I missed.

**Comment by humphd** [comment]
We recently landed a fix for this (circular dep in config.js). We should decide if this still exists and close if not.

**Comment by humphd** [comment]
See #1287 cc @tianlangwu

**Comment by klee214** [comment]
I see, thank you:)

**Comment by humphd** [comment]
@klee214 @tianlangwu are you able to confirm that it's fixed on `master` now?

**Comment by klee214** [comment]
#1262, this issue seems to be solved!

**Comment by humphd** [comment]
@klee214 thank you for investigating!  Closing.
