### ISSUE TITLE
Validate input on REST APIs with Ajv

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1277]
We don't currently validate input properly to our REST API endpoints.  Let's add [Ajv](https://ajv.js.org/) to our routes that accept data, and get schema-based validation happening on the data.

Our search is one place where we accept data, and others I can think of include:

- https://github.com/Seneca-CDOT/telescope/blob/d358f2e0950d071cbf854f1e6e02dd959380456d/src/backend/web/routes/feeds.js#L76

- https://github.com/Seneca-CDOT/telescope/blob/d358f2e0950d071cbf854f1e6e02dd959380456d/src/backend/web/routes/feeds.js#L55

- https://github.com/Seneca-CDOT/telescope/blob/d358f2e0950d071cbf854f1e6e02dd959380456d/src/backend/web/routes/feeds.js#L99

**Comment by tonyvugithub** [comment]
@humphd : Can I take over this?

**Comment by tonyvugithub** [comment]
@humphd : I just realize I can assign myself

**Comment by jiyoungsin** [comment]
would it be cool if I gave this a shot too? I have created a pull request regarding this issue, however, I am still confused on why the put request and delete request needs any validation since we are not using the req.body. The pull request can be found [here](https://github.com/Seneca-CDOT/telescope/pull/1299).

**Comment by tonyvugithub** [comment]
@jiyoungsin : I have almost completed it. You may want to look at other issue.
