### ISSUE TITLE
Search for a Post that contains "react js" triggers css changes.

### ISSUE THREAD

**Issue by VietnameZe** [Seneca-CDOT/telescope#1375]
Go to the search page in development https://dev.telescope.cdot.systems/search/ and try to type 'react js' -> hit search icon -> the top nav bar will be expanded ~1.5x in height. 

UPDATE: Also when this big weird nav bar appear, the css 'hover' text color and main page background color both being changed.

Check out 3 screenshots below to see differences:

![](https://i.imgur.com/hiuWhwD.jpg)
![](https://i.imgur.com/RMepOpl.jpg)
![](https://i.imgur.com/JUblgUi.jpg)

**Comment by PedroFonsecaDEV** [comment]
So until now, what I know about the bug is:
It's on the search page of DEV (where the bug is worse)and PROD.
It seems to happen only with the string "react js" in any upper and lower case.
If you type another string to search after the "react js" search, the page backs to normal.
When the bug happens, the folder maxcdn.bootstrapcdn.com pop-up on Chrome dev tools.
It only happens when searching for "Post."

**Comment by PedroFonsecaDEV** [comment]
This issue was solved?

**Comment by VietnameZe** [comment]
> This issue was solved?

@PedroFonsecaDEV I just checked, somehow it doesn't exist anymore
