### ISSUE TITLE
Develop a worker to parse contents from the blog's url

### ISSUE THREAD

**Issue by birtony** [Seneca-CDOT/telescope#16]
We should create a worker that would implement the following features:
- Get contents from particular blog post url
- Parse the contents into the JSON format
- Pass the generated JSON file over

Receives: url
Returns: JSON file

**Comment by c3ho** [comment]
Hi, I’ll take on this issue!

**Comment by birtony** [comment]
Great! 👍

**Comment by ImmutableBox** [comment]
Hi, I would like to aid in this issue. **JUST TO BE CLEAR,** I want to help @c3ho not take the issue. This issue can be branched out to many smaller issues, I just want to get something started for people to look at.
- - -
I did some research on how to convert XML to JSON since feeds are made up of XML.
Here are some packages I found:
-[rss-parser](https://www.npmjs.com/package/rss-parser)
-[rss-to-json](https://www.npmjs.com/package/rss-to-json)
  
 I found the package [rss-parser](https://www.npmjs.com/package/rss-parser) doesn't show all the contents of the blog (Link to my blog for more information: WIP), but [rss-to-json](https://www.npmjs.com/package/rss-to-json) works fine.
  
I will create a commit and pull request, **NOT IN HOPE THAT IT WILL GET MERGE** but to provide possible solutions for @c3ho or anyone else who wants to see the implementation.

Issue: WIP
Pull Request: WIP
