### ISSUE TITLE
Implementing Octonode, for GitHub integration

### ISSUE THREAD

**Issue by Metropass** [Seneca-CDOT/telescope#1611]
**What would you like to be added**:
Implementing the [Octonode Library](https://github.com/pksunkara/octonode) for GitHub integration 
**Why would you like this to be added**:
We've mentioned that GitHub integration for Telescope would be a good module to add; Octonode is fully compliant with [GitHub's v3-api](https://docs.github.com/en) and it's written in CoffeeScript.

**Comment by Metropass** [comment]
@humphd I know that you mentioned using webhooks.js from Octokit in #1604; would this library help with your issue in anyway? I can learn more about it to get a head-start.

**Comment by humphd** [comment]
I think this issue is pre-mature.  It jumps to an implementation without first thinking through how the feature would work.  How do we get GitHub usernames?  Where do we store them?  How do we expose this data to the front-end?  What will the front-end do with it?

I'd like to get some answers to those questions before we start bolting in libraries that do things, if we don't know what we're going to do with this yet.

**Comment by chrispinkney** [comment]
Our front end sign up implements GitHub API to fetch a GitHub profile, as such this isn't necessary anymore.
