### ISSUE TITLE
[UI 2.0] SideBar

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1687]
**What would you like to be added**:
The new sidebar for UI 2.0. Please check:  https://github.com/Seneca-CDOT/telescope/issues/1676

Let's use [MUI Icons](https://material-ui.com/components/material-icons/)

| Icon 	| Icon on MUI icons: 	|
|------	|--------------------	|
|     search 	|         `import SearchIcon from '@material-ui/icons/Search';`           	|
|   home   	|            `import HomeIcon from '@material-ui/icons/Home';`        	|
|    about us  	|          `import InfoIcon from '@material-ui/icons/Info';`          	|
|     log in 	|           `import AccountCircleIcon from '@material-ui/icons/AccountCircle';`         	|
|    dark/light theme  	|    `import InvertColorsIcon from '@material-ui/icons/InvertColors';`                	|

**Comment by DukeManh** [comment]
@PedroFonsecaDEV I think I'd try this. Just to be clear, how is the sidebar supposed to be on the banner? It looks ok on the post timeline because the background is white but the banner is an image.

**Comment by PedroFonsecaDEV** [comment]
Hey @DukeManh 
The SideBar has no Color; it's transparent. Sorry for the lack of details.

**Comment by izhuravlev** [comment]
@DukeManh Hey, can you please assign yourself for this if you decide to work on it? 
Thank you.

**Comment by DukeManh** [comment]
@izhuravlev I didn't know that what I'm supposed to do, definitely will do it next time. Thank you.

**Comment by DukeManh** [comment]
@PedroFonsecaDEV Because the background is transparent, the contrast between the icons' color and the banner image is not so clear. It is ok on the timeline though. 
<img width="840" alt="Screen Shot 2021-02-23 at 1 04 04 PM" src="https://user-images.githubusercontent.com/51073515/108888417-736fec80-75d9-11eb-872b-83af9709996e.png">
<img width="840" alt="Screen Shot 2021-02-23 at 1 03 58 PM" src="https://user-images.githubusercontent.com/51073515/108888804-b8941e80-75d9-11eb-8ecb-6858f3657882.png">

Do you have any suggestions?

**Comment by PedroFonsecaDEV** [comment]
@DukeManh, don't worry about the contrast in the `Banner` because we will have a new `Banner` too. 

Regarding the icon, you can try to find some alternative here: https://material-ui.com/components/material-icons/
But I think you are ready to go; you can send this PR, and in a follow up we change the icon.
Thanks.
