### ISSUE TITLE
Set up new domains for Telescope Microservices API services

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1704]
We're slowly adding/refactoring our Telescope back-end to use microservices.  The first such service is ready to be deployed, and we'd like to separate it out onto its own `api.*` sub-domain.

To do this, we need 2 new sub-domains to be registered:

- https://api.telescope.cdot.systems/ (for production)
- https://dev.api.telescope.cdot.systems/ (for staging)

We'd like to run these on the same box as https://telescope.cdot.systems.

@ctyler I think you're the person with the power to make this happen?  Can I get your help to create these, and we'll take it from there?  Thank you.

cc @manekenpix, @raygervais

**Comment by ctyler** [comment]
The way I interpret the initial comment on this issue, Dave, is that both of the new hostnames (not subdomains) are CNAMEs for telescope.cdot.systems -- but I would have expected that dev.api.telescope.cdot.systems would be a CNAME for dev.telescope.cdot.systems instead. (Also, I would have used api.dev.telescope.cdot.systems instead of dev.api.* but either way).

So:
(1) If you want the new names to all connected to telescope.cdot.systems, this is done. dev.api.* and api.dev.* have both been set up. This issue can be closed.
(2) Alternately, if dev.api.* (or api.dev.*) is supposed to point to dev.telescope.cdot.systems instead of t.c.s, let me know, and I'll switch it.

**Comment by humphd** [comment]
@ctyler I'm not 100% sure what the right setup is, so please advise me.  My goal is to get an `api.*` domain that I can get SSL certs setup on, and which will run on the same machine as the current setup (that it runs on the same machine is not important, it's just a detail of what we'll do).  It will allow us to access different apps from the current t.c.s 80/443 setup.

If I can do that with what you've setup, it's probably fine.  If this won't work for my use case, I'm happy for you to recommend and do some other setup.

Thanks for your advice.  This isn't my area of expertise, for sure.

**Comment by humphd** [comment]
Via Slack, it sounds like this is now fixed.
