### ISSUE TITLE
Move src/dialogue.js to src/frontend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#174]
We have a stray frontend file in `src/` but we're moving all of those files to `src/frontend/*`.  We need to move `src/dialogue.js` into `src/frontend` and also update all the files in `src/frontend` so their paths work relative to their new home (i.e., use relative paths from `index.html` so they can all find each other).

**Comment by wajeehsheikh** [comment]
I can fix this issue.

**Comment by zufishanali** [comment]
Since @humphd has mentioned updating all files in `src/frontend`, I wanted to point out that there are currently 2 `planet.css` files present in the repository. One is in `src/frontend` while the other is in `src/frontend/style`. As per issue #151, the preferred location for `planet.css` appears to be `src/frontend/style`. I wasn't sure if I should create a new issue for this.

**Comment by wajeehsheikh** [comment]
No need to create another issue.  I can change the paths for all files pointing to `src/frontend/style/planet.css `to `src/frontend/planet.css` aswell.  Unless its the issue you wanted to work on?

**Comment by zufishanali** [comment]
@wajeehsheikh Oh no, I just wanted to point it out in case. You may continue working on it. Thanks!
