### ISSUE TITLE
[UI 2.0] Text Auto-fill - Title text must adjust its font-size to fit in the title div. 

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1810]
**What would you like to be added**:
Text Auto-fill - Title text must adjust its font-size to fit in the title div. 
**Why would you like this to be added**:
We should be able to read all the titles instantly.

**Comment by PedroFonsecaDEV** [comment]
cc @yuanLeeMidori

**Comment by yuanLeeMidori** [comment]
Update after triage meeting:

As @humphd suggested, I looked into medium, wordpress, dev.to, blogger. They all use the same method to handle the long title, change to new line.

Currently, telescope title is expandable. If the title is too long, it'll be wrapped to one line with `...`, and by clicking the title, it can be expanded to show all lines with the complete title.

In my opinion, this text auto-fill should be doable (I'm still experimenting different method tho), but it'll be different from other blog website. Also, I'm worried about the auto-fill on mobile, it might bring a very small font size. I'd like to gather team's thought and see if we want to do the auto-fill.

**Comment by PedroFonsecaDEV** [comment]
> Update after triage meeting:
> 
> As @humphd suggested, I looked into medium, wordpress, dev.to, blogger. They all use the same method to handle the long title, change to new line.
> 
> Currently, telescope title is expandable. If the title is too long, it'll be wrapped to one line with `...`, and by clicking the title, it can be expanded to show all lines with the complete title.
> 
> In my opinion, this text auto-fill should be doable (I'm still experimenting different method tho), but it'll be different from other blog website. Also, I'm worried about the auto-fill on mobile, it might bring a very small font size. I'd like to gather team's thought and see if we want to do the auto-fill.

@yuanLeeMidori Sure. Let's try to have a call this week.

**Comment by yuanLeeMidori** [comment]
The reason we want to dynamically change the font-size with title length is because we want to get rid of the expand title feature.

I tried different approach (write my own function and tried different react hook plug-in) to meet the dynamically-adjust-font-size title, but the title does not react with the length and then adjust the font-size.

After the discussion with @PedroFonsecaDE, we decide to close this issue and start a new issue to remove the title-stick-on-the-top feature. In that case, the title will be shown with new line(s) if it's too long, but without sticking on the top when we read the post.
