### ISSUE TITLE
Add additional posts routes for the Post microservice

### ISSUE THREAD

**Issue by HyperTHD** [Seneca-CDOT/telescope#1865]
In #1838, I hope to land the long awaited posts microservice. The original writing of this in the backend only had 2 routes for fetching 10 posts and fetching 1 post by it's id. Once that PR lands, I plan on working to add additional routes for adding, updating, and deleting posts. This would probably involve communication with the User microservice being worked on, since deleting a post would technically not be possible since the feed would parse it again and bring it back up. 

I'll need to do further discussion about this, but this is the plan right now.

**Comment by manekenpix** [comment]
I don't think these functionalities make sense since posts are usually created on a different platform and then fetched by telescope. 
if anything, the user would add/delete/update posts in the original platform and Telescope should be able to reflect those changes.

What makes sense is to flag posts so even if a post exists in the original platform, Telescope can hide it. We already do that with feeds, but maybe it'd be interesting to do the same with posts.
Check the [feeds route](https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/routes/feeds.js)  to see how Telescope flags feeds.

**Comment by humphd** [comment]
I agree that delete is problematic, and flagging is probably more realistic, since the next feed download/parse cycle would add it back.

So maybe what we're saying is:

- `GET /posts` - gets "all" posts, based on paging
- `GET /posts/:id` - gets one post with given `id`
- `POST /posts:id` - creates/replaces a post with the given `id`.  Data is cached in Redis, Indexed in Elastic. (requires user/owner rights)
- `POST /posts/:id/flag` - flags a post so it won't be returned in results (requires admin or user/owner rights)
- `DELETE /posts/:id/flag` - removes a flag on a post (requires admin or user/owner rights)

**Comment by manekenpix** [comment]
> POST /posts:id - creates/replaces a post with the given id. Data is cached in Redis, Indexed in Elastic. (requires user/owner rights)

I think it makes more sense to create/replace a post on the platform where the blog is hosted, that way the changes will be seen by both users following the blog on that platform and Telescope. Altering a post on telescope will not change the original post, so people following the blog on the original platform will miss the changes.

**Comment by humphd** [comment]
Right, I agree, we aren't getting into the business of user content creation.  I was meaning "create/replace" in the sense of it getting added to our system from the feed parser worker.  This can happen directly to redis/elastic (like we do now) or the worker process can call the posts service to add it that way.  The nice thing about do it like that would be that it's much easier to test it.  But I'm open to either approach.

**Comment by aserputov** [comment]
@HyperTHD can this issue be closed ?

**Comment by HyperTHD** [comment]
> @HyperTHD can this issue be closed ?

This needs to be discussed some more in depth because of the supabase integration. Technically speaking, deletion operation is not feasible since the parser service would just add the post back. You'd also have to consider how integrated feeds are with posts. #1907 wants them removed from the posts service, but since a post technically has a feed required, the front-end cannot load the posts without them. That being said, since posts are grabbed from the user's blog post site, and re-indexing any posts would just update them, the routes I've wanted to implement may not be possible. Wait a bit until we get some more progress on the issue mentioned above before you close this

**Comment by aserputov** [comment]
@HyperTHD thank you

**Comment by humphd** [comment]
I think we can close this.
