### ISSUE TITLE
Author Name Bug - Replace normal hyphen with a NON-BREAKING HYPHEN

### ISSUE THREAD

**Issue by PedroFonsecaDEV** [Seneca-CDOT/telescope#1955]
**What happened**:
Right now are experiencing this: 
<img width="163" alt="Screen Shot 2021-03-15 at 8 59 18 PM" src="https://user-images.githubusercontent.com/60857409/111312115-5dcc7080-8635-11eb-9691-e8c77bb530c8.png">
<img width="201" alt="Screen Shot 2021-03-15 at 8 59 02 PM" src="https://user-images.githubusercontent.com/60857409/111312117-5dcc7080-8635-11eb-83b7-1d600a3bc482.png">

**What should have happened**:
Royce's name should have the same behaviour as David's name:
```
Royce
Ayroso-ong
``` 
NON-BREAKING HYPHEN:
https://www.toptal.com/designers/htmlarrows/punctuation/non-breaking-hyphen/

**How to reproduce it (as precise as possible)**:

**Anything else we need to know?**:

**Environment**:

- OS:
- Browser:

**Comment by humphd** [comment]
Another thing I wonder is if we should give some more width to this container, since lots of students have longer names that will always need room to wrap.

<img width="631" alt="Screen Shot 2021-03-16 at 9 20 39 AM" src="https://user-images.githubusercontent.com/427398/111315657-fa444200-8638-11eb-90e8-61addd41f1fe.png">

I took a look at the [current feed list](https://wiki.cdot.senecacollege.ca/wiki/Planet_CDOT_Feed_List) for sample data, and here are some names to consider (e.g., their length and format with spaces, dashes, and other break/wrap characters):

- Crystal de Nobrega (cldenobrega)
- Mohammed Niaz ul Haque
- George Popescu (GeorgeP)
- Emmanuel Ho Fidelino
- Ricardo Bocanegra Meza
- Claire Debika Sullivan
- Hasan (northWind) Kamal-Al-Deen
- Maria Bustos-Roman
- José Aderbal Aragão Filho
- Jamal Jalali-Dolatshahi
- Mohammad Abdullah Sajed Shadani
