### ISSUE TITLE
Use quotes from former students about open source on front page

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#1974]
I'd like to see us extract some of the best quotes from former students about their experience working on open source, and use them on the front page (probably on top of the hero banner image in place of the stats?).

Every term for years and years, students write some amazing reflections on their experiences working in open source.  I think we could pull out some quotes that would be nice to use on the site as a way to inspire the current students.  We could put a bunch in a JSON file in the front-end and show a random one.

We can get at these old posts using various queries:

- https://dev.telescope.cdot.systems/search/?text=%22open%20source%22%20reflection&filter=post
- https://dev.telescope.cdot.systems/search/?text=%22open%20source%22%20conclusion&filter=post
- https://dev.telescope.cdot.systems/search/?text=%22open%20source%22%20feelings&filter=post

etc.  If you want to be involved in this, you can go do a search, read old posts, and if you see an inspiring quote about contributing to open source, blogging, etc. put it in this issue with:

- link to post
- quote
- author

**Comment by tonyvugithub** [comment]
@humphd : I think the quotes should go with the name of the authors because if they contribute something to a project and the project mentioned their names on their front page, it will possibly make them feel proud about their work and boost their incentives to contribute to open source project in the future. Especially, the quotes we pick would be positive and unbiased ones. And I believe almost everyone would like to share to the world something they think positive about.

**Comment by HyperTHD** [comment]
Gonna see what I can do with this. Think it's safe to try this with a few quotes to begin with, then we can add some more as more quotes become available

**Comment by Metropass** [comment]
I think Chris' quote perfectly describes my fumbles with Git sometimes

"Lovely. I had to reclone my fork and continue on my way. Not the end of the world but definitely annoying."

**Comment by rjayroso** [comment]
Without context, these made me smile: 
- "Bow down to your excellence, THE KING, Abdul XD!" - [Abdulbasid Guled](https://dev.to/hyperthd/dps911-blog-6-1-7-releases-no-more-playing-around-594a)
- "I may not be a smart developer, but I love rules and deadlines and respect them." - [Yuan-Hsi Lee](https://dev.to/yuanleemidori/taking-the-first-challenge-with-nextjs-and-project-release-43hp)

I like this one in particular because it showed one of our most productive releases: 
- "And oh my goodness, there's so many commits we pushed in this release that it makes me wonder if my team and I have lives outside of open source." - [Abdulbasid Guled](https://dev.to/hyperthd/dps911-blog-2-telescope-1-5-ships-my-first-release-4a67)

**Comment by chrispinkney** [comment]
> Looking back at these last 31/2 months I feel I grew as an open source developer. I can recall the first week of this class not even knowing what open source development was[.]

Taken from https://shreenasopensource.wordpress.com/
___
> I’ve gotten to work with a team that seems dedicated to a strong development process and code quality, which in turn helps me build good habits when writing code.

Taken from https://medium.com/@juliakmdev/the-virtues-of-open-source-4cd3e080399d
___
> Overall, my experiences with [open source development] were very positive. Even when I was down, I tried to work my way back up.

Taken from our own Abdul: https://dev.to/hyperthd/4-months-of-open-source-what-i-ve-learned-from-taking-dps909-and-what-i-plan-to-do-about-dps911-next-month-1g62

**Comment by tonyvugithub** [comment]
>Wow, I finally get to start talking about Open Source again! I’m very excited just writing about this, cause I have a greater chance to work on Telescope, and my own projects. 
From https://moho472.medium.com/dps911-here-we-go-telescope-28e0b9a51f86
>I took on responsibilities that I honestly did not think I could handle, and though I still have a lot of PRs to review and issues to solve, I believe it was a step in the right direction.
From https://roycedev.medium.com/two-steps-forward-one-step-back-b0c105037a04
>Down with the Shipness, Everybody is working for the Shipend, and Stairway to Shipven. It's a joke about shipping software
From https://dev.to/chrispinkney/going-down-with-the-ship-p51

**Comment by HyperTHD** [comment]
>  I also need to keep reminding myself, that failure does not ever define who I am. It's how I come back from failure that shows what I'm really capable of.
From my blog post: https://dev.to/hyperthd/4-months-of-open-source-what-i-ve-learned-from-taking-dps909-and-what-i-plan-to-do-about-dps911-next-month-1g62

> Open Source is amazing and I hope I can keep it going even after finishing this course.
From Chris's blog post: https://dev.to/chrispinkney/going-down-with-the-ship-p51

> For example, the Login component suddenly realized that he is Special, and started a riot by not following the styling of the Header. How did I suppress the Riot? Well, I will tell you about it in my next blogpost ;)
From Ilya's blog post: https://ilya-zhurik.medium.com/bye-gatsby-episode-1-3fd63db08aa1

**Comment by humphd** [comment]
From @manekenpix on Slack, quoting @c3ho:

> If it is one thing OSD has taught me, it was to research and adapt, and maybe there might be a light at the end of it all -- Calvin Ho in https://c3ho.blogspot.com/2021/04/documentation.html

**Comment by AmasiaNalbandian** [comment]
Hello - I can do this :)

**Comment by AmasiaNalbandian** [comment]
@humphd Is there a preference on where to put in the JSON file? I was thinking under signup I create a directory for "data" and then list it under as studentQuotes.js.

the implementation is under Banner.tsx

**Comment by humphd** [comment]
I would probably put it at `src/web/src/student-quotes.json`.
