### ISSUE TITLE
Implement a way to filter active and inactive bloggers

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#22]
There is a long list of bloggers but a lot of them do not blog anymore. We should have a way to show currently active bloggers and hide the ghosts.

**Comment by jerryshueh** [comment]
Let me attempt this. For now, I'm just going to work off the queue system that Dave already implemented. I'll also start a simple config file for filters, maybe a filter.json that will allow us to define the rules of what gets displayed or not.

**Comment by jerryshueh** [comment]
So it seems that we're moving forward with JSON parsing. I've followed the development on the feed-parser and ended up at issue #108. Since I need the XMLs parsed to JSON, and I don't want to disrupt any work @robertbegna may be doing, I'll just try to blackbox the script as best as possible. For now, I'll just assume any feed data being passed around after going through the queue/ parser is in JSON format, and I'll use the attribute names from the feed-parser when reading data as well.
