### ISSUE TITLE
Wiki feed parser Testing 

### ISSUE THREAD

**Issue by nazneennahar** [Seneca-CDOT/telescope#220]
Wiki Feed parser has the JS file but needs a testing file .

**Comment by Sbaah** [comment]
Hello I would like to attempt this.

**Comment by nazneennahar** [comment]
sure :)

**Comment by humphd** [comment]
I totally missed this, and filed #265. Sorry about that.  Moving my comment over from there:

We have code to download and parse the Wiki Feed List page in [wiki-feed-parser.js](src/wiki-feed-parser.js).  However, we have no tests for it.

We need to test both `getData()` and `parseData()`.  Since these rely on the network, these jests should use mocked fetch requests.  Take a look at how [test/github.test.js](test/github.test.js) does this using [jest-fetch-mock](https://www.npmjs.com/package/jest-fetch-mock).  The idea would be to simulate a network request that returns an HTML page similar to what the wiki feed list has.  It doesn't need to be identical, and in fact, having it be more simple will allow for testing different scenarios (what if the format is wrong? what if the page is not there? what if the format of the page changes and there's no `<pre>` element, etc.).  All of these can be simulated with mock responses to force the code to behave in different ways, and make sure it works as it should.

cc @cryolis, who originally wrote this code.

**Comment by ThomasLuu00** [comment]
I'll work on this if no one has started.
