### ISSUE TITLE
Slimming Telescope Feed-Discovery Docker Image

### ISSUE THREAD

**Issue by raygervais** [Seneca-CDOT/telescope#2526]
**What would you like to be added**:

Recently, I had found https://github.com/docker-slim/docker-slim which claims to work with Node based Docker containers. If this were to work, it would improve both local and server storage requirements.

Furthermore, this may help the future plan of integrating Kubernetes clusters or moving to the cloud by reducing the storage costs of the various micro services.

**Comment by TDDR** [comment]
Related discussion  #2683

**Comment by humphd** [comment]
Modified this to be about working on the feed-discovery service first, then we can add others once we have the process in place.

**Comment by TDDR** [comment]
Waiting on #2801

**Comment by TDDR** [comment]
I've spent a few hours looking at other repos and trying to figure out the best way to go about this. Seems like most repos are using this in their yaml file responsible for publishing, and that they do it on the `build-and-push` stage. Ex:
- https://github.com/invakid404/funtoo-bot/blob/deadcad126b6748535c6cab918d112c8c855b1b0/.github/workflows/publish.yml#L82
- https://github.com/webb-tools/dkg-substrate/blob/2226aca1c9aad769e9b751eab983cf9f13bc162e/.github/workflows/image-publish.yml#L26

I think in order to do this we would have to omit [setup-buildx-action](https://github.com/Seneca-CDOT/telescope/blob/7944fa01eb87481f38573de4f949618c332b5671/.github/workflows/docker-build-and-push.yml#L104) and implement `docker-slim` are our builder. I'm not sure of the consequences of that though.

Also, instead of downloading and installing `slim` through `curl` there is the option of pulling an [image](https://github.com/docker-slim/docker-slim#docker) and having that run in our containers. Would we be able to pull that image into our registry and have it do it's thing in from there?

@humphd, @manekenpix  your feed back would be appreciated

**Comment by humphd** [comment]
I don't want to stop using `buildx`, since it's what makes all of our caching work.  Can you see if you can get this work with with buildx?  A quick scan of their repo issues didn't seem to preclude using it, unless you are cross-compiling, which we don't.

**Comment by JerryHue** [comment]
@TDDR, do you think that we can make this for 2.9? I can move it to 3.0-alpha in the case we need to more discussion.

cc @humphd, @manekenpix

**Comment by humphd** [comment]
Moving to Alpha, I want @TDDR to focus on the deploy stuff.

**Comment by humphd** [comment]
OK, thanks for looking into this.  I don't want to move away from buildx, so let's leaave this for when they do support it.

**Comment by humphd** [comment]
I don't think this is worth doing, now that we have better caching and our own registry in place.
