### ISSUE TITLE
Dashboard Build Log layout issues

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2611]
We don't have the layout quite right on the [build log dashboard page](https://dev.api.telescope.cdot.systems/v1/status/build).

First, the height of the terminal isn't right, now that we've added the build header, and it's overflowing the page:

<img width="1242" alt="Screen Shot 2021-12-14 at 2 22 02 PM" src="https://user-images.githubusercontent.com/427398/146065612-2851dd33-915d-4b03-9618-5267a4cc00dd.png">

Second, the terminal isn't expanding to fill the available width, while the build header is:

<img width="1210" alt="Screen Shot 2021-12-14 at 2 22 11 PM" src="https://user-images.githubusercontent.com/427398/146065615-48b99b18-bff8-428d-acc6-08bc26dfcb37.png">

Third, the build header should sit right on top of the terminal, and get rid of the `border-radius` on the bottom-left and bottom-right, so that it looks like the top of a window vs. something that floats.

Let's use proper CSS Flexbox or Grid to do this layout, it should be pixel perfect and responsive.

**Comment by HyperTHD** [comment]
Related to this issue, the hamburger icon for the dashboard floats to just beside the build log title at 767px rather than floating to the right as it should for most mobile views. We should also correct this as well.

This is how it looks with a max-width of 767px:
![image](https://user-images.githubusercontent.com/16841702/146121959-71d668c5-bebe-4817-aefe-ff360d843845.png)

This is how it should look like for all mobile view of this page:
![image](https://user-images.githubusercontent.com/16841702/146121755-91ccc34b-d5fa-4820-8359-97792480febc.png)

The title is not aligned with the header as well, but utilizing Flexbox here as @humphd mentioned should alleviate the issue.

**Comment by AmasiaNalbandian** [comment]
I can take this on. Should I aim for 2.5?

**Comment by humphd** [comment]
Yeah, 2.5 would be great, thanks.

**Comment by humphd** [comment]
Looks like this slipped, moving to 2.6.
