### ISSUE TITLE
Add support for YouTube feed discover to feed-discovery service

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2675]
Our feed-discovery service is designed to find a blog feed (RSS/Atom) for.a given blog URL.  We are adding support for YouTube channels, and we should include pasting a YouTube channel and getting back the feed URL.

See https://danielmiessler.com/blog/rss-feed-youtube-channel/:

Given a channel like mine, https://www.youtube.com/channel/UCqaMbMDf01BLttof1lHAo2A, the feed URL is https://www.youtube.com/feeds/videos.xml?channel_id=UCqaMbMDf01BLttof1lHAo2A

We need to extend the feed-discovery implementation to deal with YouTube and return the right link.

**Comment by JerryHue** [comment]
I would like to work on this.

**Comment by JerryHue** [comment]
@humphd, it seems that there is a test that actually tests this case:

https://github.com/Seneca-CDOT/telescope/blob/24f4ea1031f6c122641516f99cf42b2522aa0b3d/src/api/feed-discovery/test/router.test.js#L13-L39

Since the only thing that changes is the `blogUrl` and the `mockBlogUrlResponseBody`, I find that it would be redundant that changes these values to the YouTube variants.

**Comment by humphd** [comment]
Since we care about the specific YouTube case (and URL structure), let's add another test that does it, even thought it repeats aspects.  Then we'll know if we break it.
