### ISSUE TITLE
Backend fails to start after removing Redis

### ISSUE THREAD

**Issue by TueeNguyen** [Seneca-CDOT/telescope#2685]
**What happened**:

![150237254-42c81164-7da3-408f-8910-ef4a9b95765a](https://user-images.githubusercontent.com/58532267/150237715-a29daa2d-a815-48d7-8a29-e628da44f5bd.png)

PR #2615 is likely to have caused the bug

**What should have happened**:

Containers should have built and run successfully 

**How to reproduce**: 

This bug occurs when you run `pnpm start` with your Redis database being fresh, not populated. It will run normally if you have run the project before.

**Comment by TueeNguyen** [comment]
After talking to @HyperTHD, I think the problem only occurs in development. 

`satellite` returns redis connection to redis server with hostname `'redis'` but the server with that hostname doesn't exist. The redis server in the docker container has '127.0.0.1' as hostname. Below is the result when I run redis-cli in the container

![image](https://user-images.githubusercontent.com/58532267/150395035-1e5667ce-3da5-407c-8e25-d2f5dae5230c.png)

In `development.yml`, redis server probably falls back to `127:0:0:1` as it hostname
https://github.com/Seneca-CDOT/telescope/blob/321f0afe7b78bf7e0fb774719b1cb3a231ca5d8b/docker/development.yml#L72-L74

**Comment by TueeNguyen** [comment]
Posting possible solution ideas soon

**Comment by humphd** [comment]
This is an interesting problem.  I'm tempted to say that the fix for it is to leave the backend how it is now, and not bother updating it to use Satellite.

The reason for this is that the code in the backend already does the right thing if the `REDIS_URL` and `REDIS_PORT` aren't defined:

https://github.com/Seneca-CDOT/telescope/blob/dece55b1acc9c1031831160706c145d81666facb/src/backend/lib/redis.js#L9

If we use Satellite, we have to define a `REDIS_URL`, and the only way to do this is to pass in an `env` file. We used to do this with the backend, but I don't think we do now (@manekenpix am I right about that?).  So there's no easy way to pass this into the backend.

We get around this in development by re-using the config from `config/env.development` here https://github.com/Seneca-CDOT/telescope/blob/dece55b1acc9c1031831160706c145d81666facb/src/backend/lib/config.js#L8; but that doesn't work in production, which is likely why we crashed.

**Comment by HyperTHD** [comment]
Thing is, in staging/production, we've redefined the redis_url to point to the container itself, which is defined as follows:

https://github.com/Seneca-CDOT/telescope/blob/master/docker/production.yml#L41
https://github.com/Seneca-CDOT/telescope/blob/master/docker/production.yml#L177

I tried to connect to redis this way with dev while talking with @TueeNguyen to no avail, with the only way being to do so the way he mentioned above.

It's a sticky situation, the way the backend does it is fine, and honestly once the parser service gets added, we shouldn't worry about it since the backend's going to be removed. The service that uses redis, the posts service, grabs it from Satellite just fine as well

**Comment by TueeNguyen** [comment]
I'm ok with leaving backend the way it is, it's not sth we prioritize

**Comment by humphd** [comment]
I think we should focus on the parser service and fix this by removing the backend completely.  Then we don't have multiple hacks in place to make this work.

@TueeNguyen you cool if we close this?

**Comment by TueeNguyen** [comment]
Yes!

**Comment by humphd** [comment]
Thanks for doing the research and digging into this.  Even though we didn't go with this solution, having the options in front of us was really important for being able to move forward.

**Comment by TueeNguyen** [comment]
I believe someone will dig this one up for their issue :)
