### ISSUE TITLE
ElasticSearch Advanced Route is breaking Search in Production

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#2698]
**What happened**:
A new route for search was introduced in https://github.com/Seneca-CDOT/telescope/pull/2617. However one of the files which validates the query was altered so that we can do either advanced search or regular search until we refactor everything in https://github.com/Seneca-CDOT/telescope/issues/2618

```
const validateQuery = () => {
  return async (req, res, next) => {
    const rules = req.baseUrl === '/' ? queryValidationRules : advancedQueryValidationRules;

    await Promise.all(rules.map((rule) => rule.run(req)));

    const result = validationResult(req);
	@@ -45,4 +96,4 @@ const validateQuery = (rules) => {
  };
};
```
The way we are using req.base.Url is definitely incorrect and the error in console states that the query cant be validated - this should not have happened.

**What should have happened**:
Searches should go through completely fine.

**How to reproduce it (as precise as possible)**:
Go to https://telescope-ve8uhdv17-humphd.vercel.app/search/ and type a query - it returns no results.

**Anything else we need to know?**:
This was working in API, but in the search bar it is not..... explore why

**Environment**:

- OS:
- Browser:

**Comment by humphd** [comment]
cc @TDDR @JiaHua-Zou, this is a breaking change on production, so we'll need to ship a patch release, `2.5.1`, by Friday so we un-break production.  @JiaHua-Zou since @TDDR did the release today, maybe you can do this next one?  We can co-ordinate with @AmasiaNalbandian, since she needs to get a PR up and reviewed, merged on `master`, tested on staging, and then we can do a `2.5.1` release with the fix.
