### ISSUE TITLE
Start an MVP for including Twitch streams in Telescope

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#2728]
Research:

  - Twitch API integration in back-end?
  - MVP(Minimum Viable Product) of Twitch component for front-end

Look up the details for what we can do so we can potentially get started for 2.7.

**Comment by sirinoks** [comment]
[Docs](https://dev.twitch.tv/docs/embed)
It seems that a parser should recognize a twitch stream/video link and replace it with an embed of such format:
```html
<iframe
    src="https://player.twitch.tv/?<channel, video, or collection>&parent=streamernews.example.com"
    height="<height>"
    width="<width>"
    allowfullscreen="<allowfullscreen>">
</iframe>
```

**Comment by sirinoks** [comment]
I am trying to find an example of how the youtube one was implemented to use as a reference. I can't find the PR/Issue though. Could someone show me where it is?

**Comment by humphd** [comment]
cc @dbelokon, who wrote it all.

**Comment by dbelokon** [comment]
> RSS:
There is no official twitch RSS, however there is this
https://twitchrss.appspot.com/

This is perfect! It seems we can fork the project and use it in Telescope, as it uses Apache License, version 2.0, as long as we respect the License. Here's a [TL;DR of the license](https://tldrlegal.com/license/apache-license-2.0-(apache-2.0)). However, I would like to hear from @humphd for the final decision, as he is familiar with working with different open source licenses.

For the embedding, I think we can use a module like [`react-twitch-embed`](https://www.npmjs.com/package/react-twitch-embed/v/1.2.0), as it is easier to deal with in React.

**Comment by humphd** [comment]
If you want to use that app, someone needs to fix https://github.com/lzeke0/TwitchRSS/issues/18 upstream so we can pull and run their app as a container.

**Comment by sirinoks** [comment]
@dbelokon Could show to me where is the main part of the code that makes youtube work?

**Comment by dbelokon** [comment]
@sirinoks, there is no really a specific part on how the YouTube works, as it is treated like another RSS feed (thanks to the suggestions that Dave mentioned back in the review of the PR), so I can write a small guide on how the code ended up:

* First, in `src/backend`, I made a few changes to the `processor.js` so that it can parse the feed given by YouTube. I simply added a few properties for the parser to look for. After this, these articles given by the feed are converted to `Posts`, which then get saved to the redis database.
* The other important change was modifying the `posts` service so that it could add an extra property to the JSON responses. The extra property defines whether the given post is either a `blogpost` or a `video`. This is used in the front end.
* In the front end, I check which posts are videos, so I can place the embedded video player with the link of the post.

As you can see from the summary, I didn't do a huge rewrite to the backend, which is a big benefit~

Lemme know if you have any other questions 😄

**Comment by humphd** [comment]
https://hub.docker.com/r/rssbridge/rss-bridge/ is a more full-featured RSS bridge that is already containerized
