### ISSUE TITLE
React Native: Get UI library installed

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#2730]
**What would you like to be added**:
We are just looking to put in the UI libraries

**Why would you like this to be added**:

**Comment by humphd** [comment]
See discussion in https://github.com/Seneca-CDOT/telescope/discussions/2667#discussioncomment-1993433 cc @Kevan-Y

**Comment by LuigiZaccagnini** [comment]
I like [Native Base](https://nativebase.io/) because it offers a lot more UI components. Was wondering what @Kevan-Y @tpmai22 and @AmasiaNalbandian think?

**Comment by Kevan-Y** [comment]
Native Base seems to be a good choice for me since, it has a lot of components and customization

**Comment by AmasiaNalbandian** [comment]
I'm liking it too actually. Seems to have the basics.

**Comment by AmasiaNalbandian** [comment]
@aserputov @dbelokon You're up! @menghif shipped in his expo PR this morning! I think we should add the Native Base as @LuigiZaccagnini recommended! 👍

**Comment by aserputov** [comment]
@dbelokon we need to find another library.

**Comment by tpmai22** [comment]
@aserputov any reason for that ?

**Comment by aserputov** [comment]
As @tpmai22 said, let's try `React Native Elements`

**Comment by dbelokon** [comment]
> As @tpmai22 said, let's try `React Native Elements`

So, we are going with `React Native Elements`? I am not sure what the reason for it, since @tpmai22 was also wondering for the reason.

**Comment by humphd** [comment]
This hasn't been communicated well in the issue.  Today @aserputov, @menghif, and I tried to integrate Native Base UI into our tree, and it's not possible.  They seem to have bugs with the current version of React Native.  Because we had an alternative choice, we thought to try that instead.

However, it others can make Native Base UI work, we're happy to take the PR.  We just got stuck on getting something in for 2.6, and wanted to push forward.

Let us know what you'd like to do.

@aserputov this would have been good to put in the issue so others knew what was happening.

**Comment by aserputov** [comment]
@humphd can't agree more, my bad. That's a much better way than texting everybody explanations on slack

**Comment by JerryHue** [comment]
To bring forward some discussions before finally choosing the UI Library, I would like to mention three possible options:

- [React Native Elements](https://github.com/react-native-elements/react-native-elements)
- [React Native Paper](https://github.com/callstack/react-native-paper)
- [React Native UI Kitten](https://github.com/akveo/react-native-ui-kitten)

I went through the `package.json` files for these projects, so there shouldn't be a dependency issue like the one present in NativeBase.

In my opinion, I would choose React Native UI Kitten because it looks aesthetically pleasing. I know that my judgment is not factoring things like usability or elements offered, so I would like to hear other points of view.

**Comment by humphd** [comment]
I'd suggest you consider maintenance, and popularity:

https://www.npmtrends.com/react-native-elements-vs-react-native-paper-vs-react-native-ui-kitten

Based on that, I'd suggest React Native Elements.

**Comment by humphd** [comment]
You all decide, just pick something that won't go unmaintained next year when you leave me with a bunch of code...

**Comment by Kevan-Y** [comment]
Let's go with [React Native Elements](https://github.com/react-native-elements/react-native-elements). This package is maintained, I think it will last long.

**Comment by dbelokon** [comment]
I will be following up with a PR soon!
