### ISSUE TITLE
Use GITHUB_TOKEN env var in status service docker setup

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2799]
In #2789 we added Octokit for GitHub API calls to the status service.  In it, we use a `GITHUB_TOKEN` env var if present:

```js
const octokit = new MyOctokit({
  auth: process.env.GITHUB_TOKEN,
```

This requires us to define and forward this env var in docker.  We need to make a few additional changes:

- update all `env.*` files to include a `GITHUB_TOKEN=` line.   @manekenpix do we have this defined already on staging/production for the webhook (i.e., could we use an existing one)?
- update the status service's `environment` to include this variable (i.e., forward it into the container): https://github.com/Seneca-CDOT/telescope/blob/master/docker/docker-compose.yml#L18-L26

I think that's everything.  We may also want to document this somewhere.

**Comment by manekenpix** [comment]
> update all env.* files to include a GITHUB_TOKEN= line. @manekenpix do we have this defined already on staging/production for the webhook (i.e., could we use an existing one)?

It's not defined, but I think it should relatively easy to have the `autodeployment` server inject the token into the environment.
Instead of adding the token variable to the `env` files, I wonder if we could add it to the environment via:

```yaml
GITHUB_TOKEN={super_secret_token} docker-compose --env-file config/env.staging...
```

and make it accessible [here](https://github.com/Seneca-CDOT/telescope/blob/da0b0f664743f54a22e0f2605aba82aed11d0425/docker/docker-compose.yml#L18).

**Comment by humphd** [comment]
We could also use https://docs.docker.com/engine/reference/commandline/secret/ maybe?  I'm not sure if compose can use them.
