### ISSUE TITLE
Build log not filling vertical space

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2842]
The build log dashboard isn't filling the whole vertical space for me:

<img width="1210" alt="Screen Shot 2022-02-05 at 10 17 08 AM" src="https://user-images.githubusercontent.com/427398/152647678-e7f00543-b0dc-4d38-aa99-e0a1ca619158.png">

**Comment by JerryHue** [comment]
For the person who is interested on approaching this:

The build page uses `xterm.js` to show that terminal look alike. This means that a few CSS changes will not be ideal. It is preferred to use the `xterm.js` API. We may use the `resize()` function:

```ts
    /**
     * Resizes the terminal. It's best practice to debounce calls to resize,
     * this will help ensure that the pty can respond to the resize event
     * before another one occurs.
     * @param x The number of columns to resize to.
     * @param y The number of rows to resize to.
     */
    resize(columns: number, rows: number): void;
```

I am not really sure how we will get the number of rows, but we will figure it out!

**Comment by JerryHue** [comment]
So I went ahead to figure this out, and it was surprisingly simple.

The terminal is just a bunch of rows, so if we get the size of a single row, and then calculate how many rows it would take to cover a certain height, we would be able to resize the terminal with no problem!

## What we need

To calculate the number of rows required, we would need to know the height of a single row, as well as the desired height of the terminal.

- Height of a single row: This one requires that we initialize the terminal with a single row and get its height with `getBoundingClientRect()`. This is how the `xterm.js` project does it, as well.
- Desired height of terminal: container: We would have to do some math, since the desired height depends on the window size of the user, as well as the position of the container itself. Let me illustrate it: ![image](https://user-images.githubusercontent.com/53304516/152672190-b0d8b88c-6c24-4c3c-8927-adf41313d2dc.png) Since we have the size of the window, and we can get the position of the container to get its offset, we can set an arbitrary margin at the bottom to be able to calculate the desired height of the container.

With the desired height of the container and the height of a single row, we can calculate the total rows by simply dividing the height of the container by the height of the single row. Since it is not guaranteed for the number of rows to be integer, we will do a `floor` operation.

After defining this function, we can call for the first time, and call it in the event of the window getting resized. With this, we should a resizable terminal!
