### ISSUE TITLE
Figure out why we have notion.so webhooks

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#2849]
Last week we suddenly had 2 new [webhooks installed in the repo](https://github.com/Seneca-CDOT/telescope/settings/hooks/):

![image](https://user-images.githubusercontent.com/427398/152688907-5102f1e5-974f-4b7d-83db-1084ce0c863c.png)

I don't know what these are for, and I'd like to understand why they are here.  A webhook is used to send data to a web server whenever some GitHub event occurs.  In this case, it's happening for all issues in the repo.

Did someone set up a new issue tracker?  It's OK if you did, but I'd like to know the reasons so we can maintain things.

**Comment by TueeNguyen** [comment]
@Kevan-Y and I figured it out, it was me who triggered those webhooks because I have GitHub connected to Notion. I pasted some issues/pull requests to Notion, Notion keeps these embedded GitHub updated using webhooks. 

Once I disconnected my GitHub from Notion, the webhooks went away.

![image](https://user-images.githubusercontent.com/58532267/153036550-61cc8e15-2827-4d54-a680-c5cc5cb69452.png)

**Comment by manekenpix** [comment]
I still see them

![image](https://user-images.githubusercontent.com/23108901/153085379-c53f513b-250d-4e0b-9eae-9986b7e05d42.png)

Should we remove them?

cc @humphd

**Comment by Kevan-Y** [comment]
I don't think there is not much harm to having it. 
Downside:
Since it will create 1 webhook for 1 Norion.
If we have like 20 people that use Notions and connect to Github, it will generate 20 webhook.

**Comment by humphd** [comment]
Let's monitor it.  If it starts to balloon, we can remove them.  I'll close for now.

@TueeNguyen, @Kevan-Y, and anyone else using Notion, please clean up after yourself.
