### ISSUE TITLE
Update parser to fetch feeds from Supabase

### ISSUE THREAD

**Issue by Kevan-Y** [Seneca-CDOT/telescope#2861]
**What would you like to be added**:

Currently, we have a parser that fetches feed from  [CDOT Feed List](https://wiki.cdot.senecacollege.ca/wiki/Planet_CDOT_Feed_List). 
We want to update our parser to fetch feed from Supabase once https://github.com/Seneca-CDOT/telescope/issues/2860 is implemented.

**Comment by TueeNguyen** [comment]
After a discussion. We decided to to 
* Write a seed script to migrate our wiki feeds to Supabase leveraging the [`/tools/migrate/migrate.js`](https://github.com/Seneca-CDOT/telescope/blob/master/tools/migrate/migrate.js).
* After seeding, find a way to persist the data (repo level like `redis-data` for development, and higher repo level for production like `redis` in `production.yml` https://github.com/Seneca-CDOT/telescope/blob/bc01b293c2bb769825de5ef0caef21292c2e1375/docker/production.yml#L173-L177
* Modify this https://github.com/Seneca-CDOT/telescope/blob/bc01b293c2bb769825de5ef0caef21292c2e1375/src/api/parser/src/parser.js#L62 to something like
```js
// Supabase may not allow us to return all data at once, if it's the case => do it in portions
const feeds = await getWiki() // getWiki() queries feeds from Supabase
```
* For development, seeding all the feeds into Supabase may be too much, we thought of adding a small amount of feeds but this is for later

cc @humphd @DukeManh

**Comment by TueeNguyen** [comment]
Currently waiting for #3373 to merge previous test changes before I can continue to change the test to reflect on the parser's change

**Comment by humphd** [comment]
OK, #3373 is in, what's next?

**Comment by JerryHue** [comment]
This issue is related to #1907, and #3355.

**Comment by JerryHue** [comment]
I would like to point out the things we need to also target for the `parser` service:

* The parser service needs to invalidate the feeds on Supabase instead of redis.
* The parser service needs to flag feeds on Supabase instead of redis.
* The parser service does not need to `updateFeed`s anymore. Refer to:
https://github.com/Seneca-CDOT/telescope/blob/d56306a75f25622176a18730246f9ffbf588a046/src/api/parser/src/parser.js#L48
https://github.com/Seneca-CDOT/telescope/blob/d56306a75f25622176a18730246f9ffbf588a046/src/api/parser/src/parser.js#L12-L28

A few clarifications:

* Redis may keep the `etag` and `lastModified` fields, since they would not be that ergonomic in Postgres.
* Delayed feeds can be kept in Redis, since they would not be as ergonomic in Postgres.
