### ISSUE TITLE
Sign up flow not working on development

### ISSUE THREAD

**Issue by Kevan-Y** [Seneca-CDOT/telescope#2886]
**What happened**:
On development, sign-up flow not working. 
I'm getting a 400 code.

![image](https://user-images.githubusercontent.com/58233223/153661187-4f221da0-0f07-4b31-9533-4c110cebd459.png)

**How to reproduce it (as precise as possible)**:

1. git checkout master
2. pnpm i
3. pnpm services:start
4. go to http://localhost:8910/ and http://localhost:8000/
5. On local http://localhost:8000/ do the signup process.

**Environment**:

- OS: Windows 10 Pro edition

**Comment by humphd** [comment]
I can reproduce this locally.  When I look at the SSO service's logs, I see this error:

```
null value in column \"github_username\" of relation \"telescope_profiles\" violates not-null constraint"
```

I think the problem is in how we are sending the user data when we try to register, in the front-end here https://github.com/Seneca-CDOT/telescope/blob/master/src/web/src/pages/signup.tsx#L198-L205

We use `github` as an object, but we need to send `githubUsername` and `githubAvatarUrl`.  We changed these in the backend, but not the front-end, where we still are using the old style, with a `github: { username: "...", avatarUrl: "..." }` object.

**Comment by DukeManh** [comment]
That is it, this was one reason why I didn't want to update GitHub username and avatar out of the GitHub object. I wonder how the e2e test passed

**Comment by DukeManh** [comment]
Yeah, I forget about that

**Comment by DukeManh** [comment]
Delegated
