### ISSUE TITLE
Convert our GitHub docs to MDX in Next.js

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#290]
[docusaurus](https://docusaurus.io/) is a neat way to organize and maintain markdown docs. It's used in many Facebook repositories and I think we could totally implement it in our project as well.

Here is an example from [create-react-app](https://github.com/facebook/create-react-app):

All of their [markdown documents](https://github.com/facebook/create-react-app/tree/master/docusaurus/docs) show up like
![Annotation 2019-11-19 215306](https://user-images.githubusercontent.com/36822198/69205145-261fe800-0b17-11ea-9ebc-b7d131df8961.png)

https://create-react-app.dev/docs/getting-started

**Comment by cindyledev** [comment]
@SeanPrashad you're not on the assignees list for some reason so I'm tagging you here

**Comment by humphd** [comment]
Sent @SeanPrashad an invite to be a collaborator on the repo.

**Comment by cindyledev** [comment]
Mentioned by @humphd a while ago that this can be achieved using Gatsby as well.
https://www.gatsbyjs.org/docs/adding-markdown-pages/

I will likely morph this into Gatsby markdown pages in the future instead of implementing docusaurus.

**Comment by c3ho** [comment]
Let's leave this for post 1.0

**Comment by cindyledev** [comment]
Find something similar to this https://material-ui.com/components/tabs/ for Gatsby...
Idea: have this kind of set up for installation instructions for each OS

[Linux][Mac][Windows]
-------------------------
[instructions...              ]

**Comment by humphd** [comment]
Morph this into a bug about doing the same thing in next.js.  cc @chrispinkney,  related to #1463 for followup.

**Comment by cindyledev** [comment]
Once #1463 gets resolved, I'd like to progress forward with this. After so many morphs, I think MDX with Next.js will be the one to actually get implemented. 

https://nextjs.org/blog/markdown looks promising.

**Comment by izhuravlev** [comment]
cc @birtony

**Comment by chrispinkney** [comment]
So because MDX is now landed this issue could be a lot of fun for whoever wants to work on it.

NextJS can automatically generate routes for files found in the `pages` directory (see [/search](telescope.cdot.systems/search/) and [/about](telescope.cdot.systems/about/)). Because of this (and because of a Pagebase being landed) we can simply pull in the docs in the `/docs` folder, apply the pagebase, and rinse and repeat (see [this pr](https://github.com/Seneca-CDOT/telescope/pull/1769) for info on how this could happen.)

Also, this issue also depends on [UI 2.0](https://github.com/Seneca-CDOT/telescope/projects/21) as our docs that get rendered will need a touch up or sorts, thus I think this should go in after UI 2.0.

**Comment by chrispinkney** [comment]
@manekenpix Are you still curious about working on this? Anton has expressed interest in this today, maybe you guys would like to collab?

**Comment by manekenpix** [comment]
Yes, definitely :+1:
