### ISSUE TITLE
Making Supabase work in production

### ISSUE THREAD

**Issue by TueeNguyen** [Seneca-CDOT/telescope#3556]
`Kong` perhaps doesn't play right with our `nginx` which make our `parser` service in production can't interact with Supabase database.

Seeding feeds into Prod Supabase also results in the same error `An invalid response was received from the upstream server`

Related issue https://github.com/Kong/kong/issues/3314
```
{"level":30,"time":1650669868347,"pid":8,"hostname":"35bbf749cafa","msg":"Loading all feeds into feed queue for processing"}
{"level":50,"time":1650669868463,"pid":8,"hostname":"35bbf749cafa","error":{"message":"An invalid response was received from the upstream server"}}
{"level":50,"time":1650669868464,"pid":8,"hostname":"35bbf749cafa","err":{"type":"Error","message":"An invalid response was received from the upstream server","stack":"Error: An invalid response was received from the upstream server\n    at getAllFeeds (/app/src/utils/supabase.js:23:13)\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async processAllFeeds (/app/src/parser.js:62:19)"},"msg":"Error queuing feeds"}
```

**Comment by DukeManh** [comment]
Kong didn't work because it made requests to `supabase-rest` which failed to connect to the DB using the connection string.

I notice the Postgres password has a "@" in it, and that's a problem because the connection string is in the form `postgres://user:pass@host`, notice the "@" in the middle. If the password contains a "@", we'd have to escape it or use a different password.

I updated the password on the production run migration and data seeding, and it seems to be working.

@TueeNguyen, please test the production supabase and let me know
@humphd, I just used a uuid for the password, maybe you want to use a different one, it doesn't have to be a JWT.

**Comment by humphd** [comment]
Great detective work!  I've made updates to the values we put in the secret envs, and sent to @manekenpix to be set on staging and production.  Once he does that, we'll need to do new builds (e.g., push something to `master` and deploy a new tag) for them to get picked up properly.  Hopefully we can pair this with landing @DukeManh's work in #3558.

**Comment by TueeNguyen** [comment]
Seems like it's working on production now with the new password

**Comment by humphd** [comment]
@TueeNguyen only temporarily.  A push/tag will re-create the old env vars.  We need it fixed in the secrets env files for this to stick.

**Comment by TueeNguyen** [comment]
Right, I just looked at Slack's convo

**Comment by humphd** [comment]
@manekenpix reports that this is now done on staging/production.  Hurray!

We need a push/tag to update staging/production to use these, and to confirm the fix.

**Comment by humphd** [comment]
I'm going to close, and we can do follow-ups as we discover new problems.
