### ISSUE TITLE
Improve User Experience for selecting blog feeds

### ISSUE THREAD

**Issue by AmasiaNalbandian** [Seneca-CDOT/telescope#3608]
**What would you like to be REMOVED**:
Users fill the form for the blogs they would like to add. Then we fetch the blog, if found. User Experience should not require an additional click to confirm that the blog is correct. They can do this when they submit the form. 

![image](https://user-images.githubusercontent.com/77639637/168725043-952701ac-2e3d-4cae-9ccc-4e551a466c0d.png)

**Why would you like this to be added**:
User experience, and the font is too small. :P

**Comment by AmasiaNalbandian** [comment]
Also explore removing the additional clicks for #3610

**Comment by cychu42** [comment]
Hi, I would like to take on this issue.

I recall the part where it asks for GitHub info also has a similar checkbox, so I think this issue is mainly about getting rid of all the similar checkboxes for something more convenient. Perhaps one just a text of declaration in review page, like` By submitting these information, you declare to be the owner and/or maintainer of the accounts entered.`

**Comment by manekenpix** [comment]
@cychu42 :+1:
