### ISSUE TITLE
Supabase console can't connect to backend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#3645]
I'm trying to use the Supabase console at https://supabase.telescope.cdot.systems.  It's not able to connect to the backend:

<img width="1409" alt="Screen Shot 2022-09-05 at 9 10 31 AM" src="https://user-images.githubusercontent.com/427398/188457464-af624ce4-6363-4ff1-9fa0-3ca3bae6ace1.png">

In the logs, I notice that it's trying to hit http://localhost:8000/rest/v1/, which is obviously wrong.  There must be some new config setting that needs to be updated?

**Comment by Kevan-Y** [comment]
I can't reproduce on local not sure why.

Could be related to the change on Supabase side, since we are pulling the latest image.

https://github.com/supabase/cli/blob/3d08912f1fed446b764df2a5fed00010c3ae2968/internal/start/start.go#L783

Changed in https://github.com/supabase/supabase/issues/5816

Probably we need to provide `SUPABASE_REST_URL` in our `docker-compose.yml` https://github.com/Seneca-CDOT/telescope/blob/7e852e9388ae991a27871e525805f0d4600b9c11/docker/supabase/docker-compose.yml#L10-L14

**Comment by Kevan-Y** [comment]
Seems like it did not resolve the issue.

**Comment by humphd** [comment]
This is fixed by https://github.com/Seneca-CDOT/telescope/commit/dae36e46ca00ef0508677967c3a669a20d0aee24

**Comment by humphd** [comment]
We should do a patch update on prod to promote this fix.  We need to debug the sign-up issues for new students.
