### ISSUE TITLE
Tests for spam-checker might require updating

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#365]
We'll be merging a PR #329 into the project, however we don't know if tests need to be updated or new tests need to be added.

**Comment by MusaBajwa** [comment]
Hi I am going to try to fix this issue.

**Comment by Silvyre** [comment]
I looked into this.

PR #329 deals with a single line:
https://github.com/Seneca-CDOT/telescope/blob/21d63cdc2612c86be2c836fdf285227d3abb88e9/src/backend/utils/spam-checker.js#L28

This line, which defines a `noTagsDesc` variable, was simply relocated immediately before the defined variable is called:

https://github.com/Seneca-CDOT/telescope/blob/21d63cdc2612c86be2c836fdf285227d3abb88e9/src/backend/utils/spam-checker.js#L25-L34

As a result of its relocation, `noTagsDesc` may not always be defined: it is now only defined if a few conditions are met. However, this is not an issue because the calls to `noTagsDesc` are only made if the same aforementioned conditions are met.

The test coverage remains at 100%, and I do not believe this PR merits any additional testing.
