### ISSUE TITLE
Set up automatic build and push for Docker images when merging to master

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#435]
I spoke with @ctyler today about standing up a staging environment, and we agreed that the best way to get there is to leverage Docker, and do some automation.  We already have the excellent work that @Reza-Rajabi, @manekenpix, et al have done on dockerizing our app and deps.  Here's what I'd like to do to leverage this.

When we merge to `master`, I'd like to have it automatically trigger a build of our Docker image and push to https://hub.docker.com/ (NOTE: if there is another Docker registry you think we should use, I'm open to that as well).  With Docker Hub, we can use their [automated builds](https://docs.docker.com/docker-hub/builds/) and a web hook to trigger things.

The only downside I can see to this approach is that it looks like I'll have to create an individual account, and manage it that way vs. doing something more community oriented, with shared ownership.

We'll probably not really start doing this until the new year, but getting our side of this setup now would be pretty easy.

Any other advice or things I'm not aware of that might impact this?  cc @raygervais

**Comment by raygervais** [comment]
_Init Docker Hub Idea_
Thought that is a downside of Docker Hub, I wouldn't let it discourage. I can't say I have any experience with the the organization-esque side of Docker, but here's what I'm thinking we could look into. Telescope could employ the idea of creating a `Seneca CDOT` organization for example, and once initial setup is done and multiple administrators have been appointed (thus removing the burden off of you @humphd  / or whoever creates the organization), then the only real work still required is to administrate the typical account work for other users. [This is what I'm referring to.](https://docs.docker.com/docker-hub/orgs/) Through this, shared ownership hopefully could occur without hiding the containers from the open source world either.

_On the Pipeline Side_
Unsure of the primary goal of utilizing the vast multitude of CI/CD platforms (CircleCI, Travis, DockerHub) aside from exposure and experience, but I would recommend we utilize a singular one for all testing and build related, so that way the contexts and states can be programmatic. That being said, this is from an outsider's perspective (would absolutely love to drop by the class eventually!), so please correct any assumptions or malformed workflows that I may be suggesting:

```
Commit (to branch which triggers staging) -> Testing (via npm test) -> Build (via Docker) -> Push (to staging)
```

Once Telescope has a dominate CI/CD platform, implementing the above in it's entire workflow I see being advantageous. From there, the sky's the limit I'd say with the workflows we can put through these pipelines.

_On an Side Note_
Referencing your Dockerfile in `/`, I can see another common build concern: container size over time if you're doing frequent builds and pushes. This is where I'd advise [multi-stage Docker builds](https://docs.docker.com/develop/develop-images/multistage-build/) which allow you to have a container which houses all the installed node packages prebuild, which is not pushed with the final docker container layer of your application. If @Reza-Rajabi was interested in continuing development on Telescope, I'd be eager to help (and hopefully start contributing some code 💻!).

**Comment by humphd** [comment]
Let's continue this in #699, I forgot we had this issue when I filed that, but we have more info there.
