### ISSUE TITLE
Integrate inactive blog url and include logic to filter inactive feeds

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#462]
Currently we have work for the inactive blog, but we'll need smarter logic in order to filter feeds, could probably improve on this as we go.

- We will probably need a set for inactive feeds
- Include logic to designate the feeds that are in the feed set and inactive set
- The intersection between feeds and inactive sets should be designated to inactive after the current 8 tries

**Comment by c3ho** [comment]
@humphd for the `check` function in inactive-blog-filter.js can we instead check the feedId and whether it is a member using [SISMEMBER ](https://www.w3resource.com/redis/redis-sismember-key-member.php) of the INACTIVE_FEED set instead of checking using the feedUrl? I would think that both do the same thing.

**Comment by c3ho** [comment]
This changes quite a bit of stuff, will need discussion on how we should approach this. Should we create separate functions or use parameters for existing functions to determine what they should do with the feeds?

**Comment by humphd** [comment]
@c3ho I think we should use a similar solution for this to what I'm suggesting in https://github.com/Seneca-CDOT/telescope/issues/624#issuecomment-579571774.  Specifically, when a feed becomes "invalid" (maybe after we try it a bunch of times, it fails every time, and we give up on it), we set a key in Redis to indicate that.  If the feed in question has an `id` of `ebbb25abaa`, we'd do this:

```
SET t:feed:ebbb25abaa:invalid "Date and Reason why this blog is being marked invalid..."
```

NOTE: I'm using `SET` here, not `SETEX`, since this key won't ever expire.

The value of the key can be some generated message that explains why the feed was made invalid, and when.

Whenever we process a feed, we'd check on these so-called "feed status keys" to see if a feed is invalid:

```
EXISTS t:feed:ebbb25abaa:invalid
```

If this gives back a value (1 for true), we know the invalid status is set for this feed, and can stop processing it.  We can expose this on the `Feed` object like this:

```js
let feed = await Feed.byId('ebbb25abaa');
let isInvalid = await feed.isInvalid();
// isInvalid is now true or false
```

When we remove a feed from our system, we'll also need to remove the `...:invalid` keys (if they exist).

cc @Silvyre, who is working on similar code to this.
