### ISSUE TITLE
UI Enhancement: Fonts

### ISSUE THREAD

**Issue by wlto** [Seneca-CDOT/telescope#513]
This issue is a smaller issue extracted from #505.

Currently, we are using inconsistent fonts for the website. I would like us to decide on 2 base fonts for the main content and for the headings. I believe font is an important part especially in a website where users are presented with essentially a lot of content.

I'm not a font expert but I think a serif font for content (with a more subdued black colour) might be easier for users to digest. And a sans-serif font for headings so it contrasts well with the content.

Let me know what you guys think!

**Comment by wlto** [comment]
Hi guys, I'll start looking for fonts that I think would look good for Telescope.

**Comment by wlto** [comment]
Hi guys, as promised, I have combined some fonts together for everyone to check out. The body text's line height is 26px for all fonts. Of course, I'm waiting for feedback and we can definitely adjust it. Here are the samples:

# Roboto Bold & Roboto

![Roboto Bold & Roboto](https://i.imgur.com/l75sPgt.png)

# Roboto Bold & Lora

![Roboto Bold & Lora](https://i.imgur.com/Q9NXlSl.png)

# Roboto Bold & Crimson Text

![Roboto Bold & Crimson Text](https://i.imgur.com/2v9VFwJ.png)

# Roboto Bold & Noto Serif

![Roboto Bold & Noto Serif](https://i.imgur.com/NUxTdcc.png)

------

Let me know what you guys think! I personally really like Crimson Text since it looks minimal. Although the font size might be a tad smaller than the others.

**Comment by wlto** [comment]
Note: All these fonts are available for free on Google Fonts!

**Comment by humphd** [comment]
@wlto I did a bunch of research in https://github.com/Seneca-CDOT/telescope/issues/339 on fonts, sizes, line spacing, etc. by looking at well designed, popular reading sites.  Can you take a look at some of the recommendations I made in that issue and reflect it here?

In terms of fonts, I'm of two minds on this:

- Of the combos you listed, I think we want to eliminate any that use sans-serif in the body.  My choice would probably be to go with Roboto Bold & Lora.
- Having said that, I also wonder if we should be considering using a native, [system font stack](https://flaviocopes.com/css-system-fonts/) to leverage device fonts, and to decrease download times.  Maybe this is wrong, I'd be interested in other people's take.  If we create a PWA and do proper caching of fonts, loading a web font should be fast.

Also, we need to deal with monospaced text, since we'll need to show lots of `<code>` and `<pre>` in blog posts (e.g., code snippets).  We should also figure out which monospace font to use in this bug, too.

Finally, @wlto can you send me an email (david.humphrey@senecacollege.ca) so that I can invite you to our Slack channel?  I want to get you directly involved with the other developers so we can go faster.

**Comment by wlto** [comment]
Hi @humphd , yes sure, I will take a look at that issue and make the changes on Figma first. For fonts, I was using Google Fonts mainly because of unification (not sure if that's the correct word haha). Because some system fonts like Helvetica are not available on other systems, so the text will end up looking different on different systems. Also I will look for a good monospace font for the code tags as well.

**Comment by agarcia-caicedo** [comment]
I think this issue can be closed. We are currently using the fonts suggested, any further discussion can go to https://github.com/orgs/Seneca-CDOT/teams/telescope-frontend/discussions
