### ISSUE TITLE
Automatic PR deployments for frontend

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#517]
**What would you like to be added**:

I'd love to see if we can get our frontend to be auto-deployed to [Zeit Now](https://zeit.co/docs/v2/more/now-for-github) (or a similar free service) so that we can easily test frontend changes whenever someone makes a change and wants to have it get merged.

**Why would you like this to be added**:

A lot of projects use this for static portions of their app (e.g., frontend) so that they can do more responsible reviews.  No one is going to pull every PR and build/test it locally.  We need a way to automate this so that it's possible to really see the impact of a PR.

Doing this will be dependent on us separating our frontend from our express server.  Once we have a React or similar setup, this should be much easier.

**Comment by ragnarokatz** [comment]
@humphd 

So I've been playing around with this. I created an account on zeit, and I was able to do some manual deployment so far: https://frontend-zeta-beige.now.sh/

steps in order to deploy manually:
```
npm i -g now
cd src/frontend
now login
now
```

I have linked up my own fork of telescope on github with my zeit app as well. However, the automatic deployment after every PR creation does not seem to work. It is unsupported at the moment according to this source:
https://spectrum.chat/zeit/now/git-deployment-from-subdirectory~eb838339-47c8-43a9-a24b-211e197fb1f3

**Comment by humphd** [comment]
@cindyledev I notice you [can do this with Netlify as well](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/).

One thing I'm not clear on how we should do is to specify the backend URLs to use for accessing our REST/GraphQL endpoints when we do this.  We'd need to tell the version deployed to zeit/netflify to use our staging box vs. the same box serving the content.  This is somewhat related to what @agarcia-caicedo is doing in #569.  We just need some kind of flag/env variable to be able to configure gatsby with a different base URL to use when accessing backend data routes.

**Comment by humphd** [comment]
https://www.gatsbyjs.org/docs/environment-variables/ has some good ideas on this, and https://www.gatsbyjs.org/docs/environment-variables/#example gives an example very close to what we need to do.
