### ISSUE TITLE
Update 'Contributing to Telescope' section

### ISSUE THREAD

**Issue by yatsenko-julia** [Seneca-CDOT/telescope#555]
The 'Setup Telescope' in [CONTRIBUTING.md](https://github.com/Seneca-CDOT/telescope/blob/master/docs/CONTRIBUTING.md) file should be updated. With current instruction new user cannot set up Telescope properly. 

Here are things that should be changed:

- Add an explanation to the step 2. This step is unclear for people that cannot find .env file as it is hidden (Mac users),
- Remove useless steps for set up like steps 7, 8,
- Rewrite step 4 as its also unclear. 

There could be some other things that should be changed, we should discuss it.

**Comment by cindyledev** [comment]
Step 2

> Copy env.example to .env to create a new environment configuration.

Yeah, this step is explained in [Local_Login](https://github.com/Seneca-CDOT/telescope/blob/master/docs/Local_Login.md) but no one would think to look in here because the file name doesn't have 'env' in it. I'll do a formal write up once all the issues involving .env have been fixed (ie #574 )

Step 4

> 1. Start Redis using:
> 
>    - Docker: `docker-compose up -d redis`
> 
>    _To stop the Docker container for Redis, run:_ `docker-compose stop redis`
> 
>    - Native Install: `redis-service`
> 
>    _To stop Redis, ctrl+c the window running the redis server._

This can also be improved on.

Step 7-8

> IF eslint detect some issues run npm run eslint-fix before manually fixing the issue (Will save you time 😄) and then run npm test again.

> Run npm run jest-watch to watch files for any changes and rerun tests related to changed files.

You're right, this has nothing to do with the Telescope setup and shouldn't be here.

Thanks for the reporting this issue @yatsenko-julia , I'll be working on this.
