### ISSUE TITLE
Friendly error message if wiki feed URL is missing from .env

### ISSUE THREAD

**Issue by Silvyre** [Seneca-CDOT/telescope#562]
Similarly to #122, the lack of a proper `.env` setup currently results in an error logging that does not immediately indicate a cause:

![image](https://user-images.githubusercontent.com/13500769/72768899-dcab5200-3bc6-11ea-9f5c-26ecc0f85b91.png)

The current stack trace logging should be replaced with a user-friendly error message.

**Comment by humphd** [comment]
Some extra notes:

- The code is https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/utils/wiki-feed-parser.js#L14
- That `fetch()` expects an absolute URL
- If the `.env` doesn't have the right variable set, the value will be empty and cause this error
- The fix is to set `FEED_URL=https://wiki.cdot.senecacollege.ca/wiki/Planet_CDOT_Feed_List` in the `.env`

We should mention this instead of this error.

**Comment by humphd** [comment]
NOTE: The error I want to see here is slightly different from missing the `.env`, which is what I describe how to do in https://github.com/Seneca-CDOT/telescope/pull/550#pullrequestreview-346109439.  Here I'm looking for an error message that indicates that the developer is missing a URL for the wiki feed itself, which we depend on, and can't guess.

**Comment by Silvyre** [comment]
We decided that this was resolved by #550 (specifically https://github.com/Seneca-CDOT/telescope/commit/e4c5a12a32b21a76efdeaf8feede880ddb3f31d6#diff-997fe4fbd6c88492e7a8aae70ea0d74b).
