### ISSUE TITLE
Adding test instructions into CONTRIBUTING.md

### ISSUE THREAD

**Issue by ImmutableBox** [Seneca-CDOT/telescope#57]
Add instruction `npm test`, `npm run eslint`, `npm run eslint-fix` to CONTRIBUTING.md. See https://github.com/Seneca-CDOT/telescope/pull/55 for more information about the testing infrastructure.

**Comment by cindyledev** [comment]
PR #55 has merged; closing this issue.

**Comment by ragnarokatz** [comment]
@ImmutableBox I don't believe this documentation issue has been completed, please correct me if I'm wrong.

**Comment by ragnarokatz** [comment]
Please rename the section into "The list of things must be done by a contributor before filing a PR", so that it includes `jest`, `npm test`, `eslint` and whatever might be added in the future.

**Comment by ImmutableBox** [comment]
> 
> 
> @ImmutableBox I don't believe this documentation issue has been completed, please correct me if I'm wrong.

Yup, you are correct. This hasn't been implemented yet.

**Comment by ImmutableBox** [comment]
> 
> 
> Please rename the section into "The list of things must be done by a contributor before filing a PR", so that it includes `jest`, `npm test`, `eslint` and whatever might be added in the future.

The CONTRIBUTING.md already has a list of things to be done (Setting up Redis, `npm install`), this issue is only suppose to add testing instructions.

**Comment by ragnarokatz** [comment]
@ImmutableBox @humphd 
If you don't mind, can we please put this ticket on high priority and get it done/merged ASAP? I'm starting to see examples such as #76 and #106 where people are spending time fixing other people's code because the original author didn't run the linting/ tests before PR creation/subsequent merging.

Please name the section in CONTRIBUTING.md **The list of things must be done by a contributor before filing a PR**, and make it bold/stand out.
**NOTE: This has nothing to do with project setup**. This only has to do with the list of things that **needs to be done EVERY SINGLE TIM before a PR is filed**. please emphasize this in the CONTRIBUTING.md doc.

**Comment by humphd** [comment]
We really need to get #97 landed, which will stop this from happening, by running every PR through eslint/tests.  cc @kartik-budhiraja.

But I agree, someone should get a PR up that adds these instructions.  You're welcome to get the ball rolling if you want, since you already have some text above.

**Comment by ImmutableBox** [comment]
Ill get this out of our hairs. Just give me a couple of minutes.

**Comment by kartik-budhiraja** [comment]
@ImmutableBox would appreciate it if you could review PR #97 so we could get the pipeline up and running.

**Comment by ImmutableBox** [comment]
😄 

> 
> 
> @ImmutableBox would appreciate it if you could review PR #97 so we could get the pipeline up and running.

Sure. Let me finish this first.

**Comment by ImmutableBox** [comment]
Resolve in https://github.com/Seneca-CDOT/telescope/pull/114.
