### ISSUE TITLE
Discussion: Interface Design Layout Suggestion

### ISSUE THREAD

**Issue by agarcia-caicedo** [Seneca-CDOT/telescope#625]
<h2>Why we need a better design flow</h2>
In order to save time during styling process of the front-end, we should spend more time doing mock-ups and prototypes. This allows contributors working on setting up the front-end to have a better idea of how everything should look at the end, how components should interact, and what sort of functionality most elements should have.

Doing mock-ups and prototypes at this stage will also allow everyone interested to know how they can contribute. As it is, we don't have a design, but we do have issues to fix certain elements in the current front-end. This can result in wasted time when we change the layout of the interface, since it currently looks very outdated. 

Additionally, this process would make it easier for contributors to find already existing code for elements such as banners, drawers, navbars, etc., because the design ideas would be set, rather than be thought up as the design is made.

<hr>
<h2>Mock-up for the main page and menu</h2>

I got most of the assets from previous discussion. See issues #513 and #511

<h4>Hero Banner</h4>

![image](https://user-images.githubusercontent.com/49992710/73366472-00802f00-427c-11ea-91df-5213b3e0fef7.png)

<h4>Main Blog Area</h4>

![image](https://user-images.githubusercontent.com/49992710/73366498-1130a500-427c-11ea-82ca-b9c5dcbc3281.png)

<h4>Menu - Banner</h4>

![image](https://user-images.githubusercontent.com/49992710/73366689-5c4ab800-427c-11ea-9b28-cb42f6dc4ba9.png)

<h4>Menu - Blog</h4>

![image](https://user-images.githubusercontent.com/49992710/73366633-42a97080-427c-11ea-839d-28f25d00b087.png)

<h4>Hovering over buttons</h4>

![image](https://user-images.githubusercontent.com/49992710/73366767-7f756780-427c-11ea-9cce-8e91ea974197.png)

![image](https://user-images.githubusercontent.com/49992710/73366834-91570a80-427c-11ea-8f84-58ed1b6c0867.png)

**Comment by cindyledev** [comment]
_hops on the frontend bandwagon_

**Comment by humphd** [comment]
Thanks for leading this, @agarcia-caicedo.  Some thoughts I have:

- Add a way to see the Author, Date of Post, and also a link to the post (plus maybe the blog in general)
- Reduce the width of the post, increase the line height, increase the font size.  See discussion in https://github.com/Seneca-CDOT/telescope/issues/339#issue-527730366

**Comment by humphd** [comment]
cc @wlto.  We're discussing initial work on the new frontend, if you want to get involved.

**Comment by wlto** [comment]
Hi @humphd , thank you for letting me know of this issue.
@agarcia-caicedo Thanks for starting the work on re-designing the front-end. I think there's a lot of spacing that can be added here so that the content can be more readable. As for the layout, I think the top bar is taking too much space (about 10% of the viewport's height). So maybe reducing it might reveal more content for the user? 😃

**Comment by agarcia-caicedo** [comment]
Thanks for the feedback, I'll be working on an improved version later today

**Comment by cindyledev** [comment]
@agarcia-caicedo I made some modifications and messaged you on Slack last night. Lemme know what you think :)

**Comment by miggs125** [comment]
hey @agarcia-caicedo great work! I think we could make the transition between the front page and the blog area smoother. Currently, the front page has a very dark background and switching to a white and grey background immediately after seems a little abrupt. Perhaps we can use another color palette that makes this transition more seamless?

**Comment by miggs125** [comment]
I also have an idea which is up for discussion. Feedly styles their posts like so: 
![image](https://user-images.githubusercontent.com/32024054/73503494-6a8ef600-439a-11ea-991b-3a7062a6a36c.png)
What if we copy the style but make the blogs expandable and collapsible and bind that to a click event? The user would be able to obtain a quick bird's eye view of the blog posts, and read any blog without having to leave the main layout. Thoughts @humphd @agarcia-caicedo @wlto ?

**Comment by humphd** [comment]
@miggs125 I like the look of the feedly approach, but I would not like having to click through to every post (I'm a completionist, and read everything on the planet!).  That said, we could experiment with having a timeline view like this, where you click through, and also have some way to expand them all so you can scroll through them like we do now.

**Comment by wlto** [comment]
@miggs125 I agree with @humphd , I think it's better if we can just click on the post and read it. I like the Feedly layout though. Perhaps the left sidebar can be used to create reader's bookmarks or preferred categories :)

**Comment by agarcia-caicedo** [comment]
@miggs125 @humphd how would you feel about a post that are able to be collapsed, but they start off collapsed. Something like how reddit comments behave?

**Comment by cindyledev** [comment]
I just joined the front end team a couple days ago and I'm already having a hard time following along with that's going on because we have like 5 discussions going on and many issues filed with their own conversations. I think we're pondering for too long on the basic design; we need to remember that our focus for our 0.6 release is to give @humphd his [dog food]. The initial design does not need to be perfect. (https://blog.humphd.org/telescope-0-4-to-0-5/). Which means we need to be able to do the following by Feb 5:
- I have to be able to go to our staging server at http://dev.telescope.cdot.systems/.  If I can go to https://dev.telescope.cdot.systems/ instead, that's a bonus.
- The site that runs there has to be a GatsbyJS app.  If the data it hosts comes from our GraphQL API, that's a bonus
- I have to be able to login using our fake SSO service, and it needs to show me that I'm logged in somehow
- The data hosted in the GatsbyJS app has to be live, and continually updated
- I have to be able to read everyone's 0.6 blog post describing what they did, and what I need to mark

Dave has also mentioned the [Feedly side-panel before](https://github.com/Seneca-CDOT/telescope/issues/536#issuecomment-574222867)

I believe we can work on what @agarcia-caicedo has here initially and just [add]( https://github.com/Seneca-CDOT/telescope/issues/625#issuecomment-580050643)

- Add a way to see the Author, Date of Post, and also a link to the post (plus maybe the blog in general)
- Reduce the width of the post, increase the line height, increase the font size.

**Comment by humphd** [comment]
In our meeting on Wednesday, @agarcia-caicedo said that she was going to incorporate some feedback, and then "freeze" a design for 0.6.  I think we should move on this today/tomorrow, so that we have it up for everyone before we go into next week.  All other UI related work is blocked on this design.

The design we use for 0.6 is simply that: a design for the 0.6 release, and nothing more.  We can, and should keep discussing how the design will evolve.  We'll want another "frozen" design for 0.7, a different one for 0.8, 0.9, and 1.0.

Let's try to separate longer term discussions about what the design should be from "what are we shipping in this release."  I agree that having it be perfect isn't our goal; or rather, it isn't a realistic goal.  Instead, we need to make progress and keep our design "actionable" in the sense that people can implement it in the time that we have.

For 0.6, we need:

> - to be able to go to our staging server at http://dev.telescope.cdot.systems/.  If I can go to https://dev.telescope.cdot.systems/ instead, that's a bonus.
> - The site that runs there has to be a GatsbyJS app.  If the data it hosts comes from our GraphQL API, that's a bonus.
> - I have to be able to login using our fake SSO service, and it needs to show me that I'm logged in somehow
> - The data hosted in the GatsbyJS app has to be live, and continually updated
> - I have to be able to read everyone's 0.6 blog post describing what they did, and what I need to mark

If our 0.6 design can address all of these, it's probably ready to ship and be implemented.

We should probably take discussions like this one out of Issues, and do them in a meeting, or a small group of people need to do it and present it back to the community for feedback.  Rarely do "discussions as Issues" produce much fruit.  Our Issues should really be for planning actionable work: **who** will do **what** and **when**.

I think it's great that we're starting to wrestle with these ideas, and learning what works in certain settings (email, issues, Slack, in person meetings, etc) and what doesn't.  0.6 is not 1.0, and we have many release cycles left to perfect this.  Already what's happening in 0.6 is better than what happened in 0.5, and we'll continue this upward trajectory.

**Comment by miggs125** [comment]
> @miggs125 @humphd how would you feel about a post that are able to be collapsed, but they start off collapsed. Something like how reddit comments behave?

@agarcia-caicedo  this is exactly what I was thinking

**Comment by cindyledev** [comment]
We're moving discussions like this to https://github.com/orgs/Seneca-CDOT/teams/telescope-frontend/discussions, please feel free to start your own discussions about whatever topic you wanna talk about :)

**Comment by cindyledev** [comment]
Closing since there is no further discussion here.
