### ISSUE TITLE
Create a button on a page to represent the logged in status vs logged out

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#635]
**What would you like to be added**:
As there is a lot of discussion right now going on about ther design of the front end, we need to have a basic page just to start using a login button. This is just creating a page with a button. 

**Why would you like this to be added**:
The SSO shouldn't be held up by the front end design, so if we can get a base page that has a button. We are good to go.

**Comment by humphd** [comment]
Regardless of our design, this can be added to the existing fronted Gatsby app in `src/frontend`.  If we build it as some kind of "login/logout" button component in React, we can use that in the new design later, and don't need to block on anything now.

I've added this to 0.6, since we need it for this release.

**Comment by Grommers00** [comment]
Awesome sounds good!
