### ISSUE TITLE
Automatic deploys to staging on commit to master

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#699]
**What would you like to be added**:

Let's add a webhook flow for our staging deployment builds.  When we commit on the `master` branch of the  Seneca-CDOT/telescope repo, we should trigger a build process on dev.telescope.cdot.systems.

I think the way to do this is using a [GitHub webhook] for the [push event](https://developer.github.com/v3/activity/events/types/#pushevent) from our repo on GitHub.

For this to work, we'll need to have a POST route running on our telescope server (maybe at `/admin/webhooks/push`).  There are various pre-made middleware routes for this, for example [github-webhook-handler](https://www.npmjs.com/package/github-webhook-handler). We'll also need to [secure the telescope side of the webhook on our server](https://developer.github.com/webhooks/securing/), so we don't respond to push events from anyone but GitHub.

In the payload we receive, we'll have to look for `ref` to be `refs/head/master` (i.e., for a push to the master branch).  We could also do a bit of sanity checking, to get the current commit SHA and the previous commit SHA so we can compare with what's on the server's git repo (could do this in follow-up).

Then, we need to trigger an update to our git repo on the telescope server and kick off a docker rebuild.  It could be as simple as this:

```bash
#!/bin/bash
git pull origin master
docker-compose up -d
```

But I suspect @manekenpix has thoughts about what he's been doing manually that we can turn into a script that can live in our `tools/` directory.

**Why would you like this to be added**:

I want to move us toward "Continuous Delivery" and limit the amount of work we expect @manekenpix to do for us manually.  He's done an amazing job, but we can't expect him to always handle deployment.

**Comment by manekenpix** [comment]
@c3ho and I tested github webhooks using a small repo we created for testing and [github-webhook-handler](https://www.npmjs.com/package/github-webhook-handler), and it worked very well. We have some doubts about how to proceed next.
For context, these are the steps required for a manual, successful update and deployment of telescope:
```yml
- cd telescope
- Shut down telescope using docker-compose
- Remove images, containers, network... docker system prune -a
- cd ..
- Remove telescope folder
- git clone git@github.com:Seneca-CDOT/telescope.git
- cd telescope
- set up env vars
- Deploy telescope using docker compose
```
The idea is to have a clean deployment after cloning telescope.

We thought about how telescope would have to shut itself down _from within_ (maybe killing the script that'd clone and deploy telescope), and we were wondering if it'd be cleaner to have the route waiting for `POST` requests from Github _outside_ telescope (a tiny express server with just that one route).

Also, we're not sure about what the best move would be if GitHub sends a `POST` request to trigger an update when telescope is in the middle of updating and redeploying from a previous `POST` request.

We'd like to hear from the community in case anyone has an idea, previous experience or just a suggestion about these issues.

cc @humphd @raygervais

**Comment by humphd** [comment]
I wonder if the easiest way to do this is with a Green/Blue deployment pattern, where you have 2 versions of docker compose going using project names, and one is running while you are building/running the new one, then you switch over to that.

This is where Kubernetes would help us, but let's try and find a simple solution for staging.  @raygervais, what would you do?

**Comment by humphd** [comment]
Some examples of what I mean:

- https://www.maptiler.com/blog/2016/08/blue-green-deployment-with-docker-and.html
- https://coderbook.com/@marcus/how-to-do-zero-downtime-deployments-of-docker-containers/

We could put a load balancer in front of our two apps (green/blue) and let it route traffic to one while the other builds and starts, then cut over to the other one and remove the first.  In this way you reduce downtime to basically zero.

**Comment by raygervais** [comment]
I like the idea of Green/Blue deployment strategies, and I think the two links show great value in how it can be done (I prefer the simplicity of the first, but only truthfully skimmed the two). One problem that both face, similar to your load-balancer concept: They are manual steps. If we are seeking automated deployments via Blue/Green, then perhaps the only manual step should be merging to master branch. 

An thought experiment, imagine this: 

```                
                      Master ->
            Develop -^
Feature Branch -^
```

At the cost of having two branches now to ensure are up to date in each fork (_well, really only the develop branch since no one should care about master on their dedicated fork_), you now are able to create merge requests into develop, which when merged gets automatically deployed to the staging cluster. A merge into master from develop would then deploy to your live instance. This way, all can be done without ever having to touch the literal cluster since we can utilize Github's hooks to trigger the build via CI/CD, and that same build should deploy to the correct instance for example.

I'm trying (perhaps failing) to explain a 100% automation path, where the only manual step is the trigger (the merge). 

That being said, if we want to avoid this workflow, I see the load-balancer idea being best since ensures downtime is kept at a minimum and a stable build is always public. If we can find a way to automate the load-balancer, you're laughing. Netlify has a fantastic workflow for something like this where each commit triggers a preview build that can be viewed in a subdomain. Once the merge occurs to master, Netlify would then build on the master branch and publish straight away to a live instance for example.

**Comment by humphd** [comment]
@raygervais I bet we don't need the `develop` branch here at all, and can do a webhook from GitHub for merges to `master` the way you describe.  We'd use tagged releases to do something similar for production later.  I outlined some of that in the initial comment at the top.

I bet this is how we should do this, but we might decide it's too complicated for 0.7, and start work on it, knowing it might take a few releases to get in place.

**Comment by raygervais** [comment]
Apologies, though I had replied to this already and only rediscovered that I didn't when reopening browser. I agree with us not needing `develop` branch, my bad for missing that part that you described up top. Happy to help towards this.

**Comment by humphd** [comment]
@raygervais that would be great.  I know @manekenpix, @c3ho, and @miggs125 were talking in class about trying to get you more involved in the deployment stuff, with your background and experience.  I think they'd appreciate having a partner on this stuff.

**Comment by raygervais** [comment]
Has there been any further work on this specifically? Or is there other pressing deployment-tagged issues that 0.7 is focused on? I look forward to working with @manekenpix @c3ho and @miggs125 more! 🎆 💻

**Comment by c3ho** [comment]
@raygervais sorry for the silence. We're going to go with a green deployment for now just so we can get CD working. In 0.8 or 0.9 we'll try to add the green/blue deployment @manekenpix did I get this right or are you going all the way with green/blue for 0.7?

**Comment by raygervais** [comment]
That's alright @c3ho, we are all busy at times 👍. Whichever direction you go about, please point out where I can help hack on some code! Is there an issue for 0.7 green deployments?
