### ISSUE TITLE
API_URL Login redirects to dev.telescope.cdot.systems when run Locally

### ISSUE THREAD

**Issue by Grommers00** [Seneca-CDOT/telescope#732]
**What happened**: If you run the API_URL to the dev.telescope.cdot.systems and run your gatsby application locally. After logging in, it redirects you to dev.telescope.cdot.systems opposed 
to your localhost.

**What should have happened**:
It should redirect you back to your localhost.

**How to reproduce it (as precise as possible)**:
In the .env file point API_URL to dev.telescope.cdot.systems, run gatsby locally, and it tries logging in.
After a successful login, it re-direct it points you back to dev.telescope.cdot.systems opposed to
localhost:3000/ (or wherever you are hosting Gatsby)

**Environment**:
.env API_URL = dev.telescope.cdot.systems
- OS: Windows 10 (Should be any OS)
- Browser: Google Chrome (Should be all)

**Comment by humphd** [comment]
The problem here is that when you get logged in, the SSO provider sends you back to the express server's login callback, where we do a redirect:

https://github.com/Seneca-CDOT/telescope/blob/master/src/backend/web/routes/auth.js#L22 

We currently use `/` as our redirect URL, and this sends you to the root of staging.  What we need to do is somehow keep track of where you came from when you hit `/login` and send you there instead.  We'd have to put this info on `req.returnTo` in `/login` and it would work.

I'm not 100% sure how to achieve this, though.  You'll end up on the `/login` route by clicking this `<a>` in our frontend:

https://github.com/Seneca-CDOT/telescope/blob/master/src/frontend/src/components/Login/LoggedOut.jsx#L11

We'd have to get referrer info sent to the express app, or otherwise make sure the express server knew where you were coming from (maybe via query string `?returnTo=url-back-to-your-fronteend`).  Needs some thought.

**Comment by humphd** [comment]
cc @Silvyre, who made us aware of this problem in Slack.

**Comment by humphd** [comment]
I spent some time on this tonight, and I'm not sure how to solve this cleanly.  I was able to modify our backend authentication routes so that when a user is redirected to the login/logout routes, we capture the referring URL.  I then put this in the `RelayState` of the SAML request we make to the SSO server.  This data will survive the trip to the SSO, and in the POST callback, I get it back.  The code looks like this:

```js
function authenticateWithSaml() {
  return function(req, res, next) {
    // We want to remember where this login request came from,
    // so stash the original referrer in the SAML RelayState.
    // When we get a response, we'll pick it out of the POST data.
    req.query.RelayState = req.get('Referrer');
    passport.authenticate('saml')(req, res, next);
  };
}

/**
 * /auth/login/callback is where the external SAML SSO provider will redirect
 * users upon successful login.  We redirect the user back to wherever
 * they were trying to go, or to the home page
 */
router.post('/login/callback', passport.authenticate('saml'), (req, res) => {
  // If there's referrer information on the body, use that for our redirect.
  const referrer = req.body.RelayState;
  res.redirect(referrer || telescopeHomeUrl);
});

/**
 * /auth/login will allow users to authenticate with the external
 * SAML SSO provider.  We add an extra middleware to grab the originating URL
 */
router.get('/login', authenticateWithSaml());
```

This works!  But then we get into 3rd-party cookie issues in Chrome, which are about to be blocked, see https://blog.chromium.org/2019/10/developers-get-ready-for-new.html.

If we ran everything over HTTPS, we could use `SameSite=None` and `Secure` for our cookies, but the whole point of this is to run things in development over mixed HTTP/HTTPS origins.

We need to think on this a bit.
