### ISSUE TITLE
Turn Telescope into a Progressive Web App (PWA)

### ISSUE THREAD

**Issue by cindyledev** [Seneca-CDOT/telescope#801]
**What would you like to be added**:
We briefly talked about this a long time ago and I think our Gatsby website is ready to be a PWA now

**Why would you like this to be added**:
Our frontend has been incredibly improved the last few days for mobile. PWA is the next step

**Comment by humphd** [comment]
https://www.gatsbyjs.org/docs/progressive-web-app/ has some good info.  We already have the mainfest plugin, and it should be tweaked to give our app the right look and feel on mobile.

Adding a service worker would be interesting.

**Comment by Silvyre** [comment]
I'd like to collaborate on this.

**Comment by humphd** [comment]
https://alligator.io/gatsbyjs/gatsby-pwa/ is also useful.

Another thing I'd love is to be able to install the app on my phone or desktop.  Probably that will require some work to get logos in the right sizes/formats, too.

**Comment by cindyledev** [comment]
I don't wanna hog this so if anyone else wants to work on this issue, I'm definitely willing on collaborate :)

**Comment by Silvyre** [comment]
Me!

**Comment by cindyledev** [comment]
Haha wanna swap so you lead and I follow? XD idk where to start

**Comment by Silvyre** [comment]
Sure, I can give it a shot, but I should warn you that I'm relatively new to PWA stuff!

To start, I'd like to split all of the work needed into multiple issues/PRs (if possible), bearing in mind the the information supplied via the links posted by @humphd, above, as well as the feedback supplied by @humphd in #805.

**Comment by Silvyre** [comment]
Some more useful Gatsby docs: https://www.gatsbyjs.org/docs/resource-handling-and-service-workers/

**Comment by humphd** [comment]
If you want to work on this, here's what I'd focus on first: make sure that we cache files in a service worker when we load, so that the offline case works.  The Workbox stuff has a lot of builtin strategies for doing this, and I suspect that Gatsby's SW stuff is a thin wrapper around that.

The list of TODOs in general is here:

<img width="814" alt="Screen Shot 2020-04-23 at 2 39 32 PM" src="https://user-images.githubusercontent.com/427398/80136842-47767b80-8570-11ea-9eb1-255e8b143619.png">

The notes from web.dev about this: https://web.dev/works-offline/?utm_source=lighthouse&utm_medium=devtools

The Offline stuff in Gatsby is where you can hook into the Workbox caching stuff, and specify what types of files and paths to cach, see https://www.gatsbyjs.org/packages/gatsby-plugin-offline/

**Comment by humphd** [comment]
Another thing I'd love to see us experiment with is https://swr.now.sh/.

**Comment by chrispinkney** [comment]
See also #1477, this could be something that we explore for the PWA too @tonyvugithub

**Comment by chrispinkney** [comment]
@tonyvugithub Are you still interested in working on this for 1.9?

**Comment by tonyvugithub** [comment]
@chrispinkney i am
