### ISSUE TITLE
Create a Post Result Component

### ISSUE THREAD

**Issue by c3ho** [Seneca-CDOT/telescope#938]
**What would you like to be added**:
We need a Post Result Component

**Why would you like this to be added**:
Required for #911, we currently have two searches: Author and Post. We don't have a nice way to show the data for Post results.

**Comment by c3ho** [comment]
We could probably leverage the `AuthorResult` component for this issue

**Comment by humphd** [comment]
This would allow some future work, too. Doing this would fulfill the goals of what Gatsby is trying to do, since we could generate a static blog page for every single post in the database this way at build time (assuming we had a running backend during the build).

I think we probably want a "page" vs. a "component."

**Comment by humphd** [comment]
We're going to try and leverage our existing component, `src/frontend/src/components/Post/Post.jsx`.  Closing.
