### ISSUE TITLE
Improve performance of My Feeds page

### ISSUE THREAD

**Issue by humphd** [Seneca-CDOT/telescope#977]
I'm not sure what's happening, but when I try to enter a new URL for a blog feed in /myfeeds, the browser lags, and eventually shows a popup with other URLs (not sure what they are), and errors about my URL not being a feed.

This isn't a great experience.  Can we make this faster?  Are we trying to validate the feed URL?  If so, can we do that when you submit it, and let the user fix if it's wrong?

<img width="388" alt="Screen Shot 2020-04-09 at 10 44 23 PM" src="https://user-images.githubusercontent.com/427398/78957695-0f713200-7ab4-11ea-8990-6f853ac3b6fa.png">

**Comment by Silvyre** [comment]
> Are we trying to validate the feed URL? If so, can we do that when you submit it, and let the user fix if it's wrong?

Yes; we can delay validation until submission by removing the form's calls to `onBlur()` as well as passing [`instantValidate={false}`](https://github.com/NewOldMax/react-form-validator-core#validatorform) to our `<ValidatorForm>`:
https://github.com/Seneca-CDOT/telescope/blob/f602ab6b76dd490d70d2eca8521ba2c69c78bd10/src/frontend/src/pages/myfeeds.js#L152

However, from my testing, this is not the cause of the slowdowns. Instead, I suspect these slowdowns may be caused by the size/structure of the component's state.

**Comment by Silvyre** [comment]
> Instead, I suspect these slowdowns may be caused by the size/structure of the component's state.

Well, moreso the massive number of elements (many hundreds of listed feeds) being rendered to the DOM is likely the cause of the slowdown.

The solution may be implementing some sort of infinite scrolling or filtering system to mitigate the performance hit.

**Comment by Silvyre** [comment]
> The solution may be implementing some sort of infinite scrolling or filtering system to mitigate the performance hit.

We might be able to reuse the solution we've implemented for the main page, here, i.e. the 'load more button' developed by @raygervais and @Grommers00.

**Comment by humphd** [comment]
What is that popup menu showing?  We shouldn't be doing validation on a URL until it's finished being typed.  Every URL will be invalid for n-1 characters entered.
